/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param fieldId 
 * @param answers 
 */
@Serializable

data class AccessVerificationResponse (

    @SerialName(value = "fieldId") @Required val fieldId: kotlin.String,

    @SerialName(value = "answers") val answers: kotlin.collections.List<kotlin.String>? = null

)

