/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AccessVerificationResponse

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param formId 
 * @param responses 
 * @param assetClassId 
 */
@Serializable

data class AccessVerificationForm (

    @SerialName(value = "formId") @Required val formId: kotlin.String,

    @SerialName(value = "responses") @Required val responses: kotlin.collections.List<AccessVerificationResponse>,

    @SerialName(value = "assetClassId") @Required val assetClassId: kotlin.String

)

