/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class ActivationCode
 *
 * @param referral referral
 * @param code activation code
 * @param email email
 */
@Serializable

data class ActivationCodePost (

    /* referral */
    @SerialName(value = "referral") @Required val referral: kotlin.String,

    /* activation code */
    @SerialName(value = "code") val code: kotlin.String? = null,

    /* email */
    @SerialName(value = "email") val email: kotlin.String? = null

)

