/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param ids List of folder object ID to be updated
 * @param applyToNestedFiles Apply expire to files under child folders
 * @param applyTo Apply expire to folder only / files only / folder and files
 * @param expire Expire date
 */
@Serializable

data class AdminFolderPutRequest (

    /* List of folder object ID to be updated */
    @SerialName(value = "ids") @Required val ids: kotlin.collections.List<kotlin.String>,

    /* Apply expire to files under child folders */
    @SerialName(value = "applyToNestedFiles") val applyToNestedFiles: kotlin.Boolean? = null,

    /* Apply expire to folder only / files only / folder and files */
    @SerialName(value = "applyTo") val applyTo: AdminFolderPutRequest.ApplyTo? = null,

    /* Expire date */
    @SerialName(value = "expire") val expire: kotlin.String? = null

) {

    /**
     * Apply expire to folder only / files only / folder and files
     *
     * Values: FOLDERS_ONLY,FILES_ONLY,FOLDERS_AND_FILES
     */
    @Serializable
    enum class ApplyTo(val value: kotlin.String) {
        @SerialName(value = "folders_only") FOLDERS_ONLY("folders_only"),
        @SerialName(value = "files_only") FILES_ONLY("files_only"),
        @SerialName(value = "folders_and_files") FOLDERS_AND_FILES("folders_and_files");
    }
}

