/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AdminRoleGroupPolicy

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class AdminRoleGroupPolicyChanges
 *
 * @param changes policy changes to be applied
 */
@Serializable

data class AdminRoleGroupPolicyChangesPost (

    /* policy changes to be applied */
    @SerialName(value = "changes") val changes: kotlin.collections.List<AdminRoleGroupPolicy>? = null

)

