/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param ids List of file object ID to be updated
 * @param expire Expire date
 */
@Serializable

data class AdminFilePutRequest (

    /* List of file object ID to be updated */
    @SerialName(value = "ids") @Required val ids: kotlin.collections.List<kotlin.String>,

    /* Expire date */
    @SerialName(value = "expire") val expire: kotlin.String? = null

)

