/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class AdminRole
 *
 * @param id Admin role unique identifier
 * @param name Admin role name
 * @param guid Admin role guid
 * @param links 
 */
@Serializable

data class AdminRole (

    /* Admin role unique identifier */
    @SerialName(value = "id") @Required val id: kotlin.Int,

    /* Admin role name */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* Admin role guid */
    @SerialName(value = "guid") val guid: kotlin.String? = null,

    @SerialName(value = "links") val links: kotlin.String? = null

)

