/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class Bandwidth
 *
 * @param dateTime Date
 * @param eventStatus Event Status
 * @param usage Bandwidth Usage
 */
@Serializable

data class Bandwidth (

    /* Date */
    @SerialName(value = "dateTime") val dateTime: kotlin.String? = null,

    /* Event Status */
    @SerialName(value = "eventStatus") val eventStatus: kotlin.Int? = null,

    /* Bandwidth Usage */
    @SerialName(value = "usage") val usage: kotlin.Int? = null

)

