/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Folder
import org.openapitools.client.models.Permission
import org.openapitools.client.models.UserBasicInfo

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id Unique identifier of object
 * @param name Object name
 * @param parentId Parent Folder identifier
 * @param userId Unique identifier of Object creator
 * @param created Object creation date
 * @param deleted Indicates that object is deleted
 * @param permDeleted Indicates that object is permanently deleted
 * @param expire Object expiry date
 * @param modified Object modification date
 * @param parent 
 * @param permalink Object permalink
 * @param creator 
 * @param permissions Current user's permissions (Explicit field. May be retrieved only if mentioned in \"with\" parameter)
 * @param vendorDocId Vendor document id (Explicit field. May be retrieved only if mentioned in \"with\" parameter)
 * @param vendorDocName Vendor document name (Explicit field. May be retrieved only if mentioned in \"with\" parameter)
 * @param source 
 * @param links 
 */
@Serializable

data class BaseFolder (

    /* Unique identifier of object */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* Object name */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* Parent Folder identifier */
    @SerialName(value = "parentId") @Required val parentId: kotlin.String,

    /* Unique identifier of Object creator */
    @SerialName(value = "userId") @Required val userId: kotlin.String,

    /* Object creation date */
    @SerialName(value = "created") val created: kotlinx.datetime.Instant? = null,

    /* Indicates that object is deleted */
    @SerialName(value = "deleted") val deleted: kotlin.Boolean? = null,

    /* Indicates that object is permanently deleted */
    @SerialName(value = "permDeleted") val permDeleted: kotlin.Boolean? = null,

    /* Object expiry date */
    @SerialName(value = "expire") val expire: kotlinx.datetime.Instant? = null,

    /* Object modification date */
    @SerialName(value = "modified") val modified: kotlinx.datetime.Instant? = null,

    @SerialName(value = "parent") val parent: Folder? = null,

    /* Object permalink */
    @SerialName(value = "permalink") val permalink: kotlin.String? = null,

    @SerialName(value = "creator") val creator: UserBasicInfo? = null,

    /* Current user's permissions (Explicit field. May be retrieved only if mentioned in \"with\" parameter) */
    @SerialName(value = "permissions") val permissions: kotlin.collections.List<Permission>? = null,

    /* Vendor document id (Explicit field. May be retrieved only if mentioned in \"with\" parameter) */
    @SerialName(value = "vendorDocId") val vendorDocId: kotlin.String? = null,

    /* Vendor document name (Explicit field. May be retrieved only if mentioned in \"with\" parameter) */
    @SerialName(value = "vendorDocName") val vendorDocName: kotlin.String? = null,

    @SerialName(value = "source") val source: kotlin.Int? = null,

    @SerialName(value = "links") val links: kotlin.String? = null

)

