/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CardAction
import org.openapitools.client.models.CardHost

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param message 
 * @param description 
 * @param severity 
 * @param type 
 * @param actions 
 * @param `data` 
 * @param host 
 */
@Serializable

data class Card (

    @SerialName(value = "message") @Required val message: kotlin.String,

    @SerialName(value = "description") @Required val description: kotlin.String,

    @SerialName(value = "severity") @Required val severity: kotlin.String,

    @SerialName(value = "type") @Required val type: kotlin.String,

    @SerialName(value = "actions") val actions: kotlin.collections.List<CardAction>? = null,

    @SerialName(value = "data") val `data`: kotlin.String? = null,

    @SerialName(value = "host") val host: CardHost? = null

)

