/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param action Action to take (e.g. dismiss, retry, delete)
 * @param type Type of card to retrieve. Available card type(s): content_encryption,email_json_migration,event_log_partitioning_migration,system_security_scanning,events_table_monitor,appadmin_db,sysadmin_db,sysadmin_hosts
 * @param fileId List of File IDs to retry encryption
 * @param storageType Storage type for files (either 'user_files' or 'replication_files')
 * @param emailId List of Email IDs to retry migrating to JSON format
 * @param volume Volume for files
 * @param hostId Host ID
 */
@Serializable

data class CardActionPostRequest (

    /* Action to take (e.g. dismiss, retry, delete) */
    @SerialName(value = "action") @Required val action: CardActionPostRequest.Action,

    /* Type of card to retrieve. Available card type(s): content_encryption,email_json_migration,event_log_partitioning_migration,system_security_scanning,events_table_monitor,appadmin_db,sysadmin_db,sysadmin_hosts */
    @SerialName(value = "type") @Required val type: CardActionPostRequest.Type,

    /* List of File IDs to retry encryption */
    @SerialName(value = "fileId") val fileId: kotlin.collections.List<kotlin.Int>? = null,

    /* Storage type for files (either 'user_files' or 'replication_files') */
    @SerialName(value = "storageType") val storageType: kotlin.String? = null,

    /* List of Email IDs to retry migrating to JSON format */
    @SerialName(value = "emailId") val emailId: kotlin.collections.List<kotlin.Int>? = null,

    /* Volume for files */
    @SerialName(value = "volume") val volume: kotlin.String? = null,

    /* Host ID */
    @SerialName(value = "hostId") val hostId: kotlin.String? = null

) {

    /**
     * Action to take (e.g. dismiss, retry, delete)
     *
     * Values: RETRY,DELETE
     */
    @Serializable
    enum class Action(val value: kotlin.String) {
        @SerialName(value = "retry") RETRY("retry"),
        @SerialName(value = "delete") DELETE("delete");
    }
    /**
     * Type of card to retrieve. Available card type(s): content_encryption,email_json_migration,event_log_partitioning_migration,system_security_scanning,events_table_monitor,appadmin_db,sysadmin_db,sysadmin_hosts
     *
     * Values: CONTENT_ENCRYPTION,EMAIL_JSON_MIGRATION,EVENT_LOG_PARTITIONING_MIGRATION,SYSTEM_SECURITY_SCANNING,EVENTS_TABLE_MONITOR,APPADMIN_DB,SYSADMIN_DB,SYSADMIN_HOSTS
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "content_encryption") CONTENT_ENCRYPTION("content_encryption"),
        @SerialName(value = "email_json_migration") EMAIL_JSON_MIGRATION("email_json_migration"),
        @SerialName(value = "event_log_partitioning_migration") EVENT_LOG_PARTITIONING_MIGRATION("event_log_partitioning_migration"),
        @SerialName(value = "system_security_scanning") SYSTEM_SECURITY_SCANNING("system_security_scanning"),
        @SerialName(value = "events_table_monitor") EVENTS_TABLE_MONITOR("events_table_monitor"),
        @SerialName(value = "appadmin_db") APPADMIN_DB("appadmin_db"),
        @SerialName(value = "sysadmin_db") SYSADMIN_DB("sysadmin_db"),
        @SerialName(value = "sysadmin_hosts") SYSADMIN_HOSTS("sysadmin_hosts");
    }
}

