/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param remoteWipe 
 * @param retainData 
 * @param retainPermissionToSharedData 
 * @param deleteUnsharedData 
 * @param retainToUser 
 */
@Serializable

data class DataRetentionOption (

    @SerialName(value = "remoteWipe") val remoteWipe: kotlin.Boolean? = false,

    @SerialName(value = "retainData") val retainData: kotlin.Boolean? = false,

    @SerialName(value = "retainPermissionToSharedData") val retainPermissionToSharedData: kotlin.Boolean? = false,

    @SerialName(value = "deleteUnsharedData") val deleteUnsharedData: kotlin.Boolean? = false,

    @SerialName(value = "retainToUser") val retainToUser: kotlin.String? = "false"

)

