/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class Device
 *
 * @param clientId Unique identifier of client for this Device
 * @param userId Unique identifier of user for this Device
 * @param installTagId Unique identifier of install tag for this Device. Usually the serial number of Device
 * @param installName Install Tag name for this Device. e.g. Someone's IPhone
 * @param mobileKeyStore Key for encryt files on this device
 */
@Serializable

data class DevicePost (

    /* Unique identifier of client for this Device */
    @SerialName(value = "clientId") val clientId: kotlin.String? = null,

    /* Unique identifier of user for this Device */
    @SerialName(value = "userId") val userId: kotlin.String? = null,

    /* Unique identifier of install tag for this Device. Usually the serial number of Device */
    @SerialName(value = "installTagId") val installTagId: kotlin.String? = null,

    /* Install Tag name for this Device. e.g. Someone's IPhone */
    @SerialName(value = "installName") val installName: kotlin.String? = null,

    /* Key for encryt files on this device */
    @SerialName(value = "mobileKeyStore") val mobileKeyStore: kotlin.String? = null

)

