/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class ECObject
 *
 * @param id Unique identifier
 * @param parentId Unique identifier of parent for this EC Object
 * @param sourceId Source Id
 * @param path File path
 * @param ecSource EC Source (Explicit field. May be retrieved only if mentioned in \"with\" parameter)
 * @param sourceTypeId Unique Identifier of the SourceType
 */
@Serializable

data class ECObject (

    /* Unique identifier */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* Unique identifier of parent for this EC Object */
    @SerialName(value = "parentId") @Required val parentId: kotlin.String,

    /* Source Id */
    @SerialName(value = "sourceId") @Required val sourceId: kotlin.String,

    /* File path */
    @SerialName(value = "path") @Required val path: kotlin.String,

    /* EC Source (Explicit field. May be retrieved only if mentioned in \"with\" parameter) */
    @SerialName(value = "ecSource") val ecSource: kotlin.String? = null,

    /* Unique Identifier of the SourceType */
    @SerialName(value = "sourceTypeId") val sourceTypeId: kotlin.String? = null

)

