/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class ECUserSource
 *
 * @param id Unique identifier of EC Source
 * @param name EC source name
 * @param userId User Id
 * @param sourceId Source Id
 */
@Serializable

data class ECUserSource (

    /* Unique identifier of EC Source */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* EC source name */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* User Id */
    @SerialName(value = "userId") @Required val userId: kotlin.String,

    /* Source Id */
    @SerialName(value = "sourceId") @Required val sourceId: kotlin.String

)

