/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class Email
 *
 * @param status Email status
 * @param emailPackageId Email Package unique identifier
 * @param secureBody 
 * @param modifiedDate 
 * @param parentEmailId The identifier of forwarded email
 */
@Serializable

data class EmailPut (

    /* Email status */
    @SerialName(value = "status") @Required val status: EmailPut.Status,

    /* Email Package unique identifier */
    @SerialName(value = "emailPackageId") val emailPackageId: kotlin.Int? = null,

    @SerialName(value = "secureBody") val secureBody: kotlin.Boolean? = null,

    @SerialName(value = "modifiedDate") val modifiedDate: java.time.LocalDate? = null,

    /* The identifier of forwarded email */
    @SerialName(value = "parentEmailId") val parentEmailId: kotlin.Int? = null

) {

    /**
     * Email status
     *
     * Values: queued,draft,sent,error
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "queued") queued("queued"),
        @SerialName(value = "draft") draft("draft"),
        @SerialName(value = "sent") sent("sent"),
        @SerialName(value = "error") error("error");
    }
}

