/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param message Error message
 * @param code Error code
 * @param failedIds 
 * @param `field` Error field
 */
@Serializable

data class ErrorString (

    /* Error message */
    @SerialName(value = "message") val message: kotlin.String? = null,

    /* Error code */
    @SerialName(value = "code") val code: kotlin.String? = null,

    @SerialName(value = "failedIds") val failedIds: kotlin.collections.List<kotlin.String>? = null,

    /* Error field */
    @SerialName(value = "field") val `field`: kotlin.String? = null

)

