/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class FeaturesList
 *
 * @param allowSftp Whether we should allow SFTP or not.
 * @param maxStorage Max storage in bytes
 * @param storageQuota Maximum storage space that user is entitled to
 * @param setExpirationLower Allow to modify file secure link expiration
 * @param sendExternal Allow sending files to external users
 * @param linkExpiration Link expiration date in days
 * @param ldapMapping LDAP Mapping value to determine the user profile type
 * @param folderCreate Allow to create top level folders
 * @param maxLinkExpiration Upper limit allowed for secure link expiration
 * @param acNoAuth Who can download file via the secure link
 * @param acVerifyRecipient Who can download file via the secure link
 * @param excludedFileExtensions Set excluded file extensions
 * @param fileFilterExclusionGroups Set excluded file groups
 * @param fileFilterCustomFileTypes Set custom file types
 * @param secureMessageBody 
 * @param secureMessageBodyDefault 
 * @param secureContainerRequired 
 * @param returnReceipt 
 * @param returnReceiptDefault 
 * @param selfCopy 
 * @param selfCopyDefault 
 * @param includeFingerprint 
 * @param includeFingerprintDefault 
 * @param requestFile 
 * @param requestFileAllowViewableFile 
 * @param requestFileUploadAuth 
 * @param requestFileAuthDefault 
 * @param requestFileExpiration 
 * @param requestFileExpirationUserDecide 
 * @param requestFileExpirationMax 
 * @param requestFileUploadLimit 
 * @param requestFileUploadLimitUserDecide 
 * @param requestFileUploadsMax 
 * @param twoFactorAuth 
 * @param inactiveExpiration 
 * @param userCanReactivate 
 * @param cleanupInactiveAccount 
 * @param withdrawInactiveAccountFileLinks 
 * @param allowCollaboration Whether we should allow Collaboration and Shared Folders or not
 * @param sendFileLimit Upper limit allowed for number of attachments per mail.
 * @param remoteWipe Disallow Collaboration: Wipe remote devices
 * @param deleteUnsharedData Disallow Collaboration: Delete all data owned by the user
 * @param retainData Disallow Collaboration: retain the data owned by the user
 * @param retainToUser Disallow Collaboration: re-assign the data to the following user
 * @param retainPermissionToSharedData Disallow Collaboration: retain all permission to shared data
 */
@Serializable

data class FeaturesListPost (

    /* Whether we should allow SFTP or not. */
    @SerialName(value = "allowSftp") val allowSftp: kotlin.Boolean? = null,

    /* Max storage in bytes */
    @SerialName(value = "maxStorage") val maxStorage: kotlin.Int? = null,

    /* Maximum storage space that user is entitled to */
    @SerialName(value = "storageQuota") val storageQuota: kotlin.Int? = null,

    /* Allow to modify file secure link expiration */
    @SerialName(value = "setExpirationLower") val setExpirationLower: kotlin.Boolean? = null,

    /* Allow sending files to external users */
    @SerialName(value = "sendExternal") val sendExternal: kotlin.Int? = null,

    /* Link expiration date in days */
    @SerialName(value = "linkExpiration") val linkExpiration: kotlin.Int? = null,

    /* LDAP Mapping value to determine the user profile type */
    @SerialName(value = "ldapMapping") val ldapMapping: kotlin.String? = null,

    /* Allow to create top level folders */
    @SerialName(value = "folderCreate") val folderCreate: kotlin.Int? = null,

    /* Upper limit allowed for secure link expiration */
    @SerialName(value = "maxLinkExpiration") val maxLinkExpiration: kotlin.Int? = null,

    /* Who can download file via the secure link */
    @SerialName(value = "acNoAuth") val acNoAuth: kotlin.Boolean? = null,

    /* Who can download file via the secure link */
    @SerialName(value = "acVerifyRecipient") val acVerifyRecipient: kotlin.Boolean? = null,

    /* Set excluded file extensions */
    @SerialName(value = "excludedFileExtensions") val excludedFileExtensions: kotlin.collections.List<kotlin.String>? = null,

    /* Set excluded file groups */
    @SerialName(value = "fileFilterExclusionGroups") val fileFilterExclusionGroups: kotlin.collections.List<kotlin.String>? = null,

    /* Set custom file types */
    @SerialName(value = "fileFilterCustomFileTypes") val fileFilterCustomFileTypes: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "secureMessageBody") val secureMessageBody: kotlin.String? = null,

    @SerialName(value = "secureMessageBodyDefault") val secureMessageBodyDefault: kotlin.Boolean? = null,

    @SerialName(value = "secureContainerRequired") val secureContainerRequired: kotlin.Boolean? = null,

    @SerialName(value = "returnReceipt") val returnReceipt: kotlin.String? = null,

    @SerialName(value = "returnReceiptDefault") val returnReceiptDefault: kotlin.Boolean? = null,

    @SerialName(value = "selfCopy") val selfCopy: kotlin.String? = null,

    @SerialName(value = "selfCopyDefault") val selfCopyDefault: kotlin.Boolean? = null,

    @SerialName(value = "includeFingerprint") val includeFingerprint: kotlin.String? = null,

    @SerialName(value = "includeFingerprintDefault") val includeFingerprintDefault: kotlin.Boolean? = null,

    @SerialName(value = "requestFile") val requestFile: kotlin.Boolean? = null,

    @SerialName(value = "requestFileAllowViewableFile") val requestFileAllowViewableFile: kotlin.Boolean? = null,

    @SerialName(value = "requestFileUploadAuth") val requestFileUploadAuth: kotlin.String? = null,

    @SerialName(value = "requestFileAuthDefault") val requestFileAuthDefault: kotlin.String? = null,

    @SerialName(value = "requestFileExpiration") val requestFileExpiration: kotlin.Int? = null,

    @SerialName(value = "requestFileExpirationUserDecide") val requestFileExpirationUserDecide: kotlin.Boolean? = null,

    @SerialName(value = "requestFileExpirationMax") val requestFileExpirationMax: kotlin.Int? = null,

    @SerialName(value = "requestFileUploadLimit") val requestFileUploadLimit: kotlin.Int? = null,

    @SerialName(value = "requestFileUploadLimitUserDecide") val requestFileUploadLimitUserDecide: kotlin.Boolean? = null,

    @SerialName(value = "requestFileUploadsMax") val requestFileUploadsMax: kotlin.Int? = null,

    @SerialName(value = "twoFactorAuth") val twoFactorAuth: kotlin.String? = null,

    @SerialName(value = "inactiveExpiration") val inactiveExpiration: kotlin.Int? = null,

    @SerialName(value = "userCanReactivate") val userCanReactivate: kotlin.String? = null,

    @SerialName(value = "cleanupInactiveAccount") val cleanupInactiveAccount: kotlin.Boolean? = null,

    @SerialName(value = "withdrawInactiveAccountFileLinks") val withdrawInactiveAccountFileLinks: kotlin.Boolean? = null,

    /* Whether we should allow Collaboration and Shared Folders or not */
    @SerialName(value = "allowCollaboration") val allowCollaboration: kotlin.Boolean? = null,

    /* Upper limit allowed for number of attachments per mail. */
    @SerialName(value = "sendFileLimit") val sendFileLimit: kotlin.Int? = null,

    /* Disallow Collaboration: Wipe remote devices */
    @SerialName(value = "remoteWipe") val remoteWipe: kotlin.Boolean? = null,

    /* Disallow Collaboration: Delete all data owned by the user */
    @SerialName(value = "deleteUnsharedData") val deleteUnsharedData: kotlin.Boolean? = null,

    /* Disallow Collaboration: retain the data owned by the user */
    @SerialName(value = "retainData") val retainData: kotlin.Boolean? = null,

    /* Disallow Collaboration: re-assign the data to the following user */
    @SerialName(value = "retainToUser") val retainToUser: kotlin.String? = null,

    /* Disallow Collaboration: retain all permission to shared data */
    @SerialName(value = "retainPermissionToSharedData") val retainPermissionToSharedData: kotlin.Boolean? = null

)

