/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class FileCopyMove
 *
 * @param destinationFolderId Destination Folder unique identifier.     EC folders are also supported.
 * @param replace Replace the file if the same file name exists. Default value is false
 */
@Serializable

data class FileCopyMovePut (

    /* Destination Folder unique identifier.     EC folders are also supported. */
    @SerialName(value = "destinationFolderId") @Required val destinationFolderId: kotlin.String,

    /* Replace the file if the same file name exists. Default value is false */
    @SerialName(value = "replace") val replace: kotlin.Boolean? = null

)

