/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class MediaTypeGroup
 *
 * @param id Unique identifier of Media Type Group
 * @param name Media Type Group name
 * @param links 
 */
@Serializable

data class FileTypeGroup (

    /* Unique identifier of Media Type Group */
    @SerialName(value = "id") val id: kotlin.Int? = null,

    /* Media Type Group name */
    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "links") val links: kotlin.String? = null

)

