/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id Job identifier
 * @param status Job status. Status could be 'queued','working','succeeded' or 'failed'
 * @param errors The list of errors occurred during job processing
 * @param objectIds 
 */
@Serializable

data class FileAddedNotificationJob (

    /* Job identifier */
    @SerialName(value = "id") val id: kotlin.String? = null,

    /* Job status. Status could be 'queued','working','succeeded' or 'failed' */
    @SerialName(value = "status") val status: kotlin.String? = null,

    /* The list of errors occurred during job processing */
    @SerialName(value = "errors") val errors: kotlin.String? = null,

    @SerialName(value = "objectIds") val objectIds: kotlin.String? = null

)

