/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class FileType
 *
 * @param id Unique identifier of File Type
 * @param mediaTypes List of associated media types
 * @param extension Extension
 * @param groupName Group Name
 * @param links 
 */
@Serializable

data class FileType (

    /* Unique identifier of File Type */
    @SerialName(value = "id") @Required val id: kotlin.Int,

    /* List of associated media types */
    @SerialName(value = "mediaTypes") @Required val mediaTypes: kotlin.Int,

    /* Extension */
    @SerialName(value = "extension") @Required val extension: kotlin.String,

    /* Group Name */
    @SerialName(value = "groupName") @Required val groupName: kotlin.String,

    @SerialName(value = "links") val links: kotlin.String? = null

)

