/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param roleId 
 * @param ids 
 * @param message 
 * @param notify 
 * @param userIds List of new members' id recommended request size <= 100
 * @param emails List of new members' email
 */
@Serializable

data class FileMembersPostRequest (

    /*  */
    @SerialName(value = "roleId") @Required val roleId: FileMembersPostRequest.RoleId,

    @SerialName(value = "ids") @Required val ids: kotlin.collections.List<kotlin.String>,

    /*  */
    @SerialName(value = "message") val message: kotlin.String? = null,

    /*  */
    @SerialName(value = "notify") val notify: kotlin.Boolean? = null,

    /* List of new members' id recommended request size <= 100 */
    @SerialName(value = "userIds") val userIds: kotlin.collections.List<kotlin.String>? = null,

    /* List of new members' email */
    @SerialName(value = "emails") val emails: kotlin.collections.List<kotlin.String>? = null

) {

    /**
     * 
     *
     * Values: _8,_9
     */
    @Serializable
    enum class RoleId(val value: kotlin.Int) {
        @SerialName(value = "8") _8(8),
        @SerialName(value = "9") _9(9);
    }
}

