/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class FileInput
 *
 * @param clientCreated File creation date set from client
 * @param clientModified File modify date set from client
 * @param note Indicates whether the file is note
 */
@Serializable

data class FileInputPost (

    /* File creation date set from client */
    @SerialName(value = "clientCreated") val clientCreated: kotlin.String? = null,

    /* File modify date set from client */
    @SerialName(value = "clientModified") val clientModified: kotlin.String? = null,

    /* Indicates whether the file is note */
    @SerialName(value = "note") val note: kotlin.Boolean? = null

)

