/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param supportedIds List of supported IDs
 */
@Serializable

data class FilePreviewSupport (

    /* List of supported IDs */
    @SerialName(value = "supportedIds") val supportedIds: kotlin.collections.List<kotlin.String>? = null

)

