/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class FilePermissions
 *
 * @param fileId Id of file
 * @param fileGuid Guid of file
 * @param permissions 
 */
@Serializable

data class FilePermissionsPut (

    /* Id of file */
    @SerialName(value = "fileId") val fileId: kotlin.Int? = null,

    /* Guid of file */
    @SerialName(value = "fileGuid") val fileGuid: kotlin.String? = null,

    @SerialName(value = "permissions") val permissions: kotlin.collections.List<kotlin.String>? = null

)

