/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class FolderCreate
 *
 * @param name Folder name
 * @param secure Indicates whether folder is secure.      * Only top level folders under user's root folder can be set to secure
 * @param isSalesforceRoot 
 * @param systemFolder 
 * @param syncable Indicates that folder is syncable. Can only be set at a top level folder.
 * @param expire The folder expiration date. Applicable to top level folders
 * @param fileLifetime The file's lifetime in the folder
 * @param description Folder description
 * @param isFolderUpload Indicate whether is folder upload children (for internal use only)
 */
@Serializable

data class FolderCreatePut (

    /* Folder name */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* Indicates whether folder is secure.      * Only top level folders under user's root folder can be set to secure */
    @SerialName(value = "secure") val secure: kotlin.Boolean? = null,

    /*  */
    @SerialName(value = "isSalesforceRoot") val isSalesforceRoot: kotlin.Boolean? = null,

    @SerialName(value = "systemFolder") val systemFolder: kotlin.Int? = null,

    /* Indicates that folder is syncable. Can only be set at a top level folder. */
    @SerialName(value = "syncable") val syncable: kotlin.Boolean? = null,

    /* The folder expiration date. Applicable to top level folders */
    @SerialName(value = "expire") val expire: kotlin.String? = null,

    /* The file's lifetime in the folder */
    @SerialName(value = "fileLifetime") val fileLifetime: kotlin.Int? = null,

    /* Folder description */
    @SerialName(value = "description") val description: kotlin.String? = null,

    /* Indicate whether is folder upload children (for internal use only) */
    @SerialName(value = "isFolderUpload") val isFolderUpload: kotlin.Boolean? = null

)

