/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Member
import org.openapitools.client.models.Permission
import org.openapitools.client.models.Role
import org.openapitools.client.models.UserBasic

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param created 
 * @param permalink 
 * @param isFavorite 
 * @param isLdapGroupMember 
 * @param isUnderMyFolder 
 * @param vendorDocId 
 * @param description 
 * @param pushedFilesCount 
 * @param creator 
 * @param expire 
 * @param pathIds 
 * @param dlpStatus 
 * @param fileLifetime 
 * @param totalFilesCount 
 * @param members 
 * @param permDeleted 
 * @param userId 
 * @param totalMembersCount 
 * @param maxFileLifetime 
 * @param maxFolderExpiration 
 * @param parentId 
 * @param secure 
 * @param id 
 * @param syncable 
 * @param rootId 
 * @param totalFoldersCount 
 * @param currentUserRole 
 * @param isRoot 
 * @param deleted 
 * @param avStatus 
 * @param name 
 * @param path 
 * @param isShared 
 * @param permissions 
 * @param modified 
 * @param source 
 * @param vendorDocName 
 * @param type 
 */
@Serializable

data class Folder (

    @SerialName(value = "created") val created: kotlin.String? = null,

    @SerialName(value = "permalink") val permalink: kotlin.String? = null,

    @SerialName(value = "isFavorite") val isFavorite: kotlin.Boolean? = null,

    @SerialName(value = "isLdapGroupMember") val isLdapGroupMember: kotlin.Boolean? = null,

    @SerialName(value = "isUnderMyFolder") val isUnderMyFolder: kotlin.Boolean? = null,

    @SerialName(value = "vendorDocId") val vendorDocId: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "pushedFilesCount") val pushedFilesCount: kotlin.Int? = null,

    @SerialName(value = "creator") val creator: UserBasic? = null,

    @SerialName(value = "expire") val expire: kotlin.String? = null,

    @SerialName(value = "pathIds") val pathIds: kotlin.String? = null,

    @SerialName(value = "dlpStatus") val dlpStatus: kotlin.String? = null,

    @SerialName(value = "fileLifetime") val fileLifetime: kotlin.Int? = null,

    @SerialName(value = "totalFilesCount") val totalFilesCount: kotlin.Int? = null,

    @SerialName(value = "members") val members: kotlin.collections.List<Member>? = null,

    @SerialName(value = "permDeleted") val permDeleted: kotlin.Boolean? = null,

    @SerialName(value = "userId") val userId: kotlin.String? = null,

    @SerialName(value = "totalMembersCount") val totalMembersCount: kotlin.Int? = null,

    @SerialName(value = "maxFileLifetime") val maxFileLifetime: kotlin.Int? = null,

    @SerialName(value = "maxFolderExpiration") val maxFolderExpiration: kotlin.String? = null,

    @SerialName(value = "parentId") val parentId: kotlin.String? = null,

    @SerialName(value = "secure") val secure: kotlin.Boolean? = null,

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "syncable") val syncable: kotlin.Boolean? = null,

    @SerialName(value = "rootId") val rootId: kotlin.String? = null,

    @SerialName(value = "totalFoldersCount") val totalFoldersCount: kotlin.Int? = null,

    @SerialName(value = "currentUserRole") val currentUserRole: Role? = null,

    @SerialName(value = "isRoot") val isRoot: kotlin.Boolean? = null,

    @SerialName(value = "deleted") val deleted: kotlin.Boolean? = null,

    @SerialName(value = "avStatus") val avStatus: kotlin.String? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "path") val path: kotlin.String? = null,

    @SerialName(value = "isShared") val isShared: kotlin.Boolean? = null,

    @SerialName(value = "permissions") val permissions: kotlin.collections.List<Permission>? = null,

    @SerialName(value = "modified") val modified: kotlin.String? = null,

    @SerialName(value = "source") val source: kotlin.Int? = null,

    @SerialName(value = "vendorDocName") val vendorDocName: kotlin.String? = null,

    @SerialName(value = "type") val type: kotlin.String? = null

)

