/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param totalDeletedFoldersCount 
 * @param total 
 * @param limit 
 * @param totalDeletedFilesCount 
 * @param offset 
 */
@Serializable

data class FoldersMetaData (

    @SerialName(value = "totalDeletedFoldersCount") val totalDeletedFoldersCount: kotlin.Int? = null,

    @SerialName(value = "total") val total: kotlin.Int? = null,

    @SerialName(value = "limit") val limit: kotlin.Int? = null,

    @SerialName(value = "totalDeletedFilesCount") val totalDeletedFilesCount: kotlin.Int? = null,

    @SerialName(value = "offset") val offset: kotlin.Int? = null

)

