/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ContactItemPost

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class Group
 *
 * @param name Contact name
 * @param items List of emails contained by Contact
 */
@Serializable

data class GroupPut (

    /* Contact name */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* List of emails contained by Contact */
    @SerialName(value = "items") @Required val items: kotlin.collections.List<ContactItemPost>

)

