/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param email LDAP Group email
 * @param description LDAP Group description
 * @param name LDAP Group name
 * @param dn LDAP Group domain name
 * @param id LDAP Group ID
 */
@Serializable

data class Group (

    /* LDAP Group email */
    @SerialName(value = "email") val email: kotlin.String? = null,

    /* LDAP Group description */
    @SerialName(value = "description") val description: kotlin.String? = null,

    /* LDAP Group name */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* LDAP Group domain name */
    @SerialName(value = "dn") val dn: kotlin.String? = null,

    /* LDAP Group ID */
    @SerialName(value = "id") val id: kotlin.Int? = null

)

