/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class Hostname
 *
 * @param id Hostname unique identifier
 * @param hostname Hostname
 * @param deleted Indicates whether the hostname is deleted
 * @param disabled Indicates whether the hostname is disabled
 * @param links 
 */
@Serializable

data class Hostname (

    /* Hostname unique identifier */
    @SerialName(value = "id") @Required val id: kotlin.Int,

    /* Hostname */
    @SerialName(value = "hostname") val hostname: kotlin.String? = null,

    /* Indicates whether the hostname is deleted */
    @SerialName(value = "deleted") val deleted: kotlin.Boolean? = null,

    /* Indicates whether the hostname is disabled */
    @SerialName(value = "disabled") val disabled: kotlin.Boolean? = null,

    @SerialName(value = "links") val links: kotlin.String? = null

)

