/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class Preview
 *
 * @param viewUrl View Url
 * @param status Raw Url
 * @param static Static Url
 * @param rawUrl Raw Url
 */
@Serializable

data class KitepointPreview (

    /* View Url */
    @SerialName(value = "viewUrl") val viewUrl: kotlin.String? = null,

    /* Raw Url */
    @SerialName(value = "status") val status: kotlin.String? = null,

    /* Static Url */
    @SerialName(value = "static") val static: kotlin.String? = null,

    /* Raw Url */
    @SerialName(value = "rawUrl") val rawUrl: kotlin.String? = null

)

