/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.LdapSearchResultUser

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class LdapSearchResults
 *
 * @param matches Search matches
 */
@Serializable

data class LdapSearchResults (

    /* Search matches */
    @SerialName(value = "matches") @Required val matches: kotlin.collections.List<LdapSearchResultUser>

)

