/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class Location
 *
 * @param name Location name. Ask administrator for location names for your server
 * @param domain A URL domain that can be used to access the servers in this location,                                  e.g. location.domain.com.                                     The domain should be registered in a DNS to point to the servers.
 */
@Serializable

data class LocationPut (

    /* Location name. Ask administrator for location names for your server */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* A URL domain that can be used to access the servers in this location,                                  e.g. location.domain.com.                                     The domain should be registered in a DNS to point to the servers. */
    @SerialName(value = "domain") @Required val domain: kotlin.String

)

