/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.EmailReturnRecipient
import org.openapitools.client.models.Package
import org.openapitools.client.models.Recipient
import org.openapitools.client.models.TrackingAccessRecipient
import org.openapitools.client.models.UserBasic

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param attachmentCount 
 * @param `package` 
 * @param darkModeStyle 
 * @param variables 
 * @param hasTrackingAccess 
 * @param sharedMailboxId 
 * @param headline 
 * @param actor 
 * @param exists 
 * @param secureBody 
 * @param webFormFields 
 * @param templateId 
 * @param recipients 
 * @param trackingAccess 
 * @param webFormId 
 * @param watermark 
 * @param emailFrom 
 * @param htmlBody 
 * @param sender 
 * @param dlpStatus 
 * @param body 
 * @param status 
 * @param date 
 * @param isPreview 
 * @param subject 
 * @param fullHtmlBody 
 * @param id 
 * @param emailReturnReceipt 
 * @param rawBody 
 * @param deleted 
 * @param avStatus 
 * @param isRead 
 * @param parentEmailId 
 * @param bucket 
 * @param notice 
 * @param isUserSent 
 * @param templateBody 
 * @param error 
 * @param expirationDate 
 * @param type 
 * @param senderId 
 * @param modifiedDate 
 * @param emailPackageId 
 */
@Serializable

data class Mail (

    @SerialName(value = "attachmentCount") val attachmentCount: kotlin.String? = null,

    @SerialName(value = "package") val `package`: Package? = null,

    @SerialName(value = "darkModeStyle") val darkModeStyle: kotlin.String? = null,

    @SerialName(value = "variables") val variables: kotlin.String? = null,

    @SerialName(value = "hasTrackingAccess") val hasTrackingAccess: kotlin.Boolean? = null,

    @SerialName(value = "sharedMailboxId") val sharedMailboxId: kotlin.String? = null,

    @SerialName(value = "headline") val headline: kotlin.String? = null,

    @SerialName(value = "actor") val actor: UserBasic? = null,

    @SerialName(value = "exists") val exists: kotlin.Boolean? = null,

    @SerialName(value = "secureBody") val secureBody: kotlin.Boolean? = null,

    @SerialName(value = "webFormFields") val webFormFields: kotlin.String? = null,

    @SerialName(value = "templateId") val templateId: kotlin.Int? = null,

    @SerialName(value = "recipients") val recipients: kotlin.collections.List<Recipient>? = null,

    @SerialName(value = "trackingAccess") val trackingAccess: kotlin.collections.List<TrackingAccessRecipient>? = null,

    @SerialName(value = "webFormId") val webFormId: kotlin.String? = null,

    @SerialName(value = "watermark") val watermark: kotlin.String? = null,

    @SerialName(value = "emailFrom") val emailFrom: kotlin.String? = null,

    @SerialName(value = "htmlBody") val htmlBody: kotlin.String? = null,

    @SerialName(value = "sender") val sender: UserBasic? = null,

    @SerialName(value = "dlpStatus") val dlpStatus: kotlin.String? = null,

    @SerialName(value = "body") val body: kotlin.String? = null,

    @SerialName(value = "status") val status: kotlin.String? = null,

    @SerialName(value = "date") val date: kotlin.String? = null,

    @SerialName(value = "isPreview") val isPreview: kotlin.Boolean? = null,

    @SerialName(value = "subject") val subject: kotlin.String? = null,

    @SerialName(value = "fullHtmlBody") val fullHtmlBody: kotlin.String? = null,

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "emailReturnReceipt") val emailReturnReceipt: kotlin.collections.List<EmailReturnRecipient>? = null,

    @SerialName(value = "rawBody") val rawBody: kotlin.String? = null,

    @SerialName(value = "deleted") val deleted: kotlin.Boolean? = null,

    @SerialName(value = "avStatus") val avStatus: kotlin.String? = null,

    @SerialName(value = "isRead") val isRead: kotlin.Boolean? = null,

    @SerialName(value = "parentEmailId") val parentEmailId: kotlin.String? = null,

    @SerialName(value = "bucket") val bucket: kotlin.String? = null,

    @SerialName(value = "notice") val notice: kotlin.String? = null,

    @SerialName(value = "isUserSent") val isUserSent: kotlin.Boolean? = null,

    @SerialName(value = "templateBody") val templateBody: kotlin.String? = null,

    @SerialName(value = "error") val error: kotlin.String? = null,

    @SerialName(value = "expirationDate") val expirationDate: kotlin.String? = null,

    @SerialName(value = "type") val type: kotlin.String? = null,

    @SerialName(value = "senderId") val senderId: kotlin.String? = null,

    @SerialName(value = "modifiedDate") val modifiedDate: kotlin.String? = null,

    @SerialName(value = "emailPackageId") val emailPackageId: kotlin.String? = null

)

