/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param subject 
 * @param body 
 * @param parentEmailId 
 * @param emailPackageId 
 * @param senderId 
 * @param sharedMailboxId 
 */
@Serializable

data class Mail2 (

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "subject") val subject: kotlin.String? = null,

    @SerialName(value = "body") val body: kotlin.String? = null,

    @SerialName(value = "parentEmailId") val parentEmailId: kotlin.String? = null,

    @SerialName(value = "emailPackageId") val emailPackageId: kotlin.String? = null,

    @SerialName(value = "senderId") val senderId: kotlin.String? = null,

    @SerialName(value = "sharedMailboxId") val sharedMailboxId: kotlin.String? = null

)

