/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class Member
 *
 * @param roleId Unique identifier of role
 * @param notifyFileAdded 
 * @param notify Indicates whether user would like to receive emails when new member is added into folder
 */
@Serializable

data class MemberPut (

    /* Unique identifier of role */
    @SerialName(value = "roleId") @Required val roleId: kotlin.Int,

    @SerialName(value = "notifyFileAdded") val notifyFileAdded: kotlin.Boolean? = null,

    /* Indicates whether user would like to receive emails when new member is added into folder */
    @SerialName(value = "notify") val notify: kotlin.Boolean? = true

)

