/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class MemberBulk
 *
 * @param roleId Role id
 * @param notify Indicates whether user would like to receive emails when new member is added into folder
 * @param emails Member emails
 * @param userIds User Ids
 * @param ldapGroupIds Member group ids
 * @param notifyFileAdded 
 */
@Serializable

data class MemberBulkPut (

    /* Role id */
    @SerialName(value = "roleId") @Required val roleId: kotlin.Int,

    /* Indicates whether user would like to receive emails when new member is added into folder */
    @SerialName(value = "notify") val notify: kotlin.Boolean? = true,

    /* Member emails */
    @SerialName(value = "emails") val emails: kotlin.collections.List<kotlin.String>? = null,

    /* User Ids */
    @SerialName(value = "userIds") val userIds: kotlin.collections.List<kotlin.String>? = null,

    /* Member group ids */
    @SerialName(value = "ldapGroupIds") val ldapGroupIds: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "notifyFileAdded") val notifyFileAdded: kotlin.Boolean? = null

)

