/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Fingerprint
import org.openapitools.client.models.PushedObject
import org.openapitools.client.models.SyncedObject
import org.openapitools.client.models.UserBasic

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param syncedObject 
 * @param fileId 
 * @param avStatus 
 * @param pushUser 
 * @param toBeNotified Indicates that Email notification for this item was sent
 * @param file 
 * @param userId 
 * @param created Mobile sync item creation date
 * @param fingerprints List of all file fingerprints
 * @param pushUserId 
 * @param fingerprint MD5 file fingerprint
 * @param pushedObject 
 * @param secure Indicates that File is in secure Folder
 * @param id Unique identifier of MobileSync
 * @param dlpStatus 
 */
@Serializable

data class MobileSync (

    @SerialName(value = "syncedObject") val syncedObject: SyncedObject? = null,

    @SerialName(value = "fileId") val fileId: kotlin.String? = null,

    @SerialName(value = "avStatus") val avStatus: kotlin.String? = null,

    @SerialName(value = "pushUser") val pushUser: UserBasic? = null,

    /* Indicates that Email notification for this item was sent */
    @SerialName(value = "toBeNotified") val toBeNotified: kotlin.Boolean? = null,

    @SerialName(value = "file") val file: org.openapitools.client.infrastructure.OctetByteArray? = null,

    @SerialName(value = "userId") val userId: kotlin.String? = null,

    /* Mobile sync item creation date */
    @SerialName(value = "created") val created: kotlin.String? = null,

    /* List of all file fingerprints */
    @SerialName(value = "fingerprints") val fingerprints: kotlin.collections.List<Fingerprint>? = null,

    @SerialName(value = "pushUserId") val pushUserId: kotlin.String? = null,

    /* MD5 file fingerprint */
    @SerialName(value = "fingerprint") val fingerprint: kotlin.String? = null,

    @SerialName(value = "pushedObject") val pushedObject: PushedObject? = null,

    /* Indicates that File is in secure Folder */
    @SerialName(value = "secure") val secure: kotlin.Boolean? = null,

    /* Unique identifier of MobileSync */
    @SerialName(value = "id") val id: kotlin.Int? = null,

    @SerialName(value = "dlpStatus") val dlpStatus: kotlin.String? = null

)

