/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param scheme 
 * @param userId 
 * @param schemeSupport 
 * @param service 
 * @param wopiSrc 
 */
@Serializable

data class MobileInfo (

    @SerialName(value = "scheme") val scheme: kotlin.String? = null,

    @SerialName(value = "userId") val userId: kotlin.String? = null,

    @SerialName(value = "schemeSupport") val schemeSupport: kotlin.String? = null,

    @SerialName(value = "service") val service: kotlin.String? = null,

    @SerialName(value = "wopiSrc") val wopiSrc: kotlin.String? = null

)

