/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class O365Client
 *
 * @param client Outlookweb/Officeweb
 */
@Serializable

data class O365ClientPost (

    /* Outlookweb/Officeweb */
    @SerialName(value = "client") @Required val client: kotlin.String

)

