/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class OnPremiseSourceLogin
 *
 * @param login Login
 * @param password Password
 */
@Serializable

data class OnPremiseSourceLoginPut (

    /* Login */
    @SerialName(value = "login") @Required val login: kotlin.String,

    /* Password */
    @SerialName(value = "password") @Required val password: kotlin.String

)

