/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Fingerprint
import org.openapitools.client.models.Folder
import org.openapitools.client.models.Member
import org.openapitools.client.models.MobileInfo
import org.openapitools.client.models.Permission
import org.openapitools.client.models.PushedObject
import org.openapitools.client.models.Tag
import org.openapitools.client.models.UserBasic
import org.openapitools.client.infrastructure.OctetByteArray

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param sharedBy 
 * @param created 
 * @param mime 
 * @param permalink 
 * @param parent 
 * @param modifier 
 * @param locked 
 * @param tags 
 * @param vendorDocId 
 * @param creator 
 * @param expire 
 * @param sharedTime 
 * @param adminQuarantineStatus 
 * @param pathIds 
 * @param dlpStatus 
 * @param lockUser 
 * @param members 
 * @param permDeleted 
 * @param userId 
 * @param clientModified 
 * @param overriddenExpire 
 * @param fingerprint 
 * @param parentId 
 * @param secure 
 * @param id 
 * @param wopiapp 
 * @param propertySize 
 * @param deleted 
 * @param avStatus 
 * @param name 
 * @param path 
 * @param fingerprints 
 * @param isShared 
 * @param lastModifiedBy 
 * @param pushedObject 
 * @param permissions 
 * @param modified 
 * @param pushed 
 * @param source 
 * @param vendorDocName 
 * @param type 
 * @param clientCreated 
 */
@Serializable

data class OctetByteArray (

    @SerialName("sharedBy") val sharedBy: UserBasic? = null,

    @SerialName("created") val created: kotlin.String? = null,

    @SerialName("mime") val mime: kotlin.String? = null,

    @SerialName("permalink") val permalink: kotlin.String? = null,

    @SerialName("parent") val parent: Folder? = null,

    @SerialName("modifier") val modifier: UserBasic? = null,

    @SerialName("locked") val locked: kotlin.Boolean? = null,

    @SerialName("tags") val tags: kotlin.collections.List<Tag>? = null,

    @SerialName("vendorDocId") val vendorDocId: kotlin.String? = null,

    @SerialName("creator") val creator: UserBasic? = null,

    @SerialName("expire") val expire: kotlin.String? = null,

    @SerialName("sharedTime") val sharedTime: kotlin.String? = null,

    @SerialName("adminQuarantineStatus") val adminQuarantineStatus: kotlin.String? = null,

    @SerialName("pathIds") val pathIds: kotlin.String? = null,

    @SerialName("dlpStatus") val dlpStatus: kotlin.String? = null,

    @SerialName("lockUser") val lockUser: UserBasic? = null,

    @SerialName("members") val members: kotlin.collections.List<Member>? = null,

    @SerialName("permDeleted") val permDeleted: kotlin.Boolean? = null,

    @SerialName("userId") val userId: kotlin.String? = null,

    @SerialName("clientModified") val clientModified: kotlin.String? = null,

    @SerialName("overriddenExpire") val overriddenExpire: kotlin.Boolean? = null,

    @SerialName("fingerprint") val fingerprint: kotlin.String? = null,

    @SerialName("parentId") val parentId: kotlin.String? = null,

    @SerialName("secure") val secure: kotlin.Boolean? = null,

    @SerialName("id") val id: kotlin.String? = null,

    @SerialName("wopiapp") val wopiapp: MobileInfo? = null,

    @SerialName("size") val propertySize: kotlin.Int? = null,

    @SerialName("deleted") val deleted: kotlin.Boolean? = null,

    @SerialName("avStatus") val avStatus: kotlin.String? = null,

    @SerialName("name") val name: kotlin.String? = null,

    @SerialName("path") val path: kotlin.String? = null,

    @SerialName("fingerprints") val fingerprints: kotlin.collections.List<Fingerprint>? = null,

    @SerialName("isShared") val isShared: kotlin.Boolean? = null,

    @SerialName("lastModifiedBy") val lastModifiedBy: UserBasic? = null,

    @SerialName("pushedObject") val pushedObject: PushedObject? = null,

    @SerialName("permissions") val permissions: kotlin.collections.List<Permission>? = null,

    @SerialName("modified") val modified: kotlin.String? = null,

    @SerialName("pushed") val pushed: kotlin.Boolean? = null,

    @SerialName("source") val source: kotlin.Int? = null,

    @SerialName("vendorDocName") val vendorDocName: kotlin.String? = null,

    @SerialName("type") val type: kotlin.String? = null,

    @SerialName("clientCreated") val clientCreated: kotlin.String? = null,

)

