/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class Package
 *
 * @param selfCopy Send a copy of the Email to yourself. True or False
 * @param includeFingerprint Include file fingerprint in email
 * @param expire Expiration date of package in hours
 * @param fileCount Set number of files included in the Email package
 * @param deleted Whether this Email package was deleted or not
 * @param acl Indicates whether the recipient is required to sign in (verify_recipient)      *                  or if they can download without signing in (no_auth)
 */
@Serializable

data class PackagePost (

    /* Send a copy of the Email to yourself. True or False */
    @SerialName(value = "selfCopy") val selfCopy: kotlin.Boolean? = null,

    /* Include file fingerprint in email */
    @SerialName(value = "includeFingerprint") val includeFingerprint: kotlin.Boolean? = null,

    /* Expiration date of package in hours */
    @SerialName(value = "expire") val expire: kotlin.String? = null,

    /* Set number of files included in the Email package */
    @SerialName(value = "fileCount") val fileCount: kotlin.Int? = null,

    /* Whether this Email package was deleted or not */
    @SerialName(value = "deleted") val deleted: kotlin.Boolean? = null,

    /* Indicates whether the recipient is required to sign in (verify_recipient)      *                  or if they can download without signing in (no_auth) */
    @SerialName(value = "acl") val acl: PackagePost.Acl? = null

) {

    /**
     * Indicates whether the recipient is required to sign in (verify_recipient)      *                  or if they can download without signing in (no_auth)
     *
     * Values: VERIFY_RECIPIENT,NO_AUTH,OTP,INTERNAL,ANYONE_AUTH
     */
    @Serializable
    enum class Acl(val value: kotlin.String) {
        @SerialName(value = "verify_recipient") VERIFY_RECIPIENT("verify_recipient"),
        @SerialName(value = "no_auth") NO_AUTH("no_auth"),
        @SerialName(value = "otp") OTP("otp"),
        @SerialName(value = "internal") INTERNAL("internal"),
        @SerialName(value = "anyone_auth") ANYONE_AUTH("anyone_auth");
    }
}

