/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ProfileMapping

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class ProfileMappings
 *
 * @param ldap Get the ldap policy filters for the user profile
 * @param kiteworks Get the kiteworks policy filters for the user profile
 * @param sso Get the ldap policy filters for the user profile
 */
@Serializable

data class ProfileMappings (

    /* Get the ldap policy filters for the user profile */
    @SerialName(value = "ldap") val ldap: kotlin.collections.List<ProfileMapping>? = null,

    /* Get the kiteworks policy filters for the user profile */
    @SerialName(value = "kiteworks") val kiteworks: kotlin.collections.List<ProfileMapping>? = null,

    /* Get the ldap policy filters for the user profile */
    @SerialName(value = "sso") val sso: kotlin.collections.List<ProfileMapping>? = null

)

