/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class ProfileMapping
 *
 * @param impact Get the User Profile mapping order
 * @param id Get the id of the target authentication source
 * @param name Get the name of the target authentication source
 * @param filter Get the filter of the target authentication source
 */
@Serializable

data class ProfileMapping (

    /* Get the User Profile mapping order */
    @SerialName(value = "impact") @Required val impact: kotlin.collections.List<kotlin.String>,

    /* Get the id of the target authentication source */
    @SerialName(value = "id") val id: kotlin.String? = null,

    /* Get the name of the target authentication source */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* Get the filter of the target authentication source */
    @SerialName(value = "filter") val filter: kotlin.String? = null

)

