/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.FeaturesList

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class Profile
 *
 * @param id Unique Profile identifier
 * @param name Profile name
 * @param prototype Prototype Profile identifier
 * @param builtIn Indicates that the profile is built in
 * @param cloneable Indicates that the profile can be a prototype for new custom profiles
 * @param features 
 */
@Serializable

data class Profile (

    /* Unique Profile identifier */
    @SerialName(value = "id") @Required val id: kotlin.Int,

    /* Profile name */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* Prototype Profile identifier */
    @SerialName(value = "prototype") @Required val prototype: kotlin.Int,

    /* Indicates that the profile is built in */
    @SerialName(value = "builtIn") @Required val builtIn: kotlin.Int,

    /* Indicates that the profile can be a prototype for new custom profiles */
    @SerialName(value = "cloneable") @Required val cloneable: kotlin.Int,

    @SerialName(value = "features") val features: FeaturesList? = null

)

