/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param folderId Folder Id
 * @param subfolders Include subfolders
 * @param folderRegex regex applied on folder paths
 */
@Serializable

data class PubSubFile (

    /* Folder Id */
    @SerialName(value = "folderId") @Required val folderId: kotlin.String,

    /* Include subfolders */
    @SerialName(value = "subfolders") val subfolders: kotlin.Boolean? = null,

    /* regex applied on folder paths */
    @SerialName(value = "folderRegex") val folderRegex: kotlin.String? = null

)

