/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.UserBasic

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param email 
 * @param userId 
 * @param type 
 * @param isDistributionList 
 * @param user 
 */
@Serializable

data class Recipient (

    @SerialName(value = "email") val email: kotlin.String? = null,

    @SerialName(value = "userId") val userId: kotlin.String? = null,

    @SerialName(value = "type") val type: kotlin.Int? = null,

    @SerialName(value = "isDistributionList") val isDistributionList: kotlin.Boolean? = null,

    @SerialName(value = "user") val user: UserBasic? = null

)

