/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Mail2
import org.openapitools.client.models.RequestFileConfig
import org.openapitools.client.models.UserBasic1

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param requestor 
 * @param fileLimit 
 * @param email 
 * @param message 
 * @param uploadLink 
 * @param config 
 * @param remaining 
 * @param expire 
 * @param id 
 * @param type 
 * @param requireAuth 
 * @param recipient 
 */
@Serializable

data class RequestFile (

    @SerialName(value = "requestor") val requestor: UserBasic1? = null,

    @SerialName(value = "fileLimit") val fileLimit: kotlin.Int? = null,

    @SerialName(value = "email") val email: Mail2? = null,

    @SerialName(value = "message") val message: kotlin.String? = null,

    @SerialName(value = "uploadLink") val uploadLink: kotlin.String? = null,

    @SerialName(value = "config") val config: RequestFileConfig? = null,

    @SerialName(value = "remaining") val remaining: kotlin.Int? = null,

    @SerialName(value = "expire") val expire: kotlin.String? = null,

    @SerialName(value = "id") val id: kotlin.Int? = null,

    @SerialName(value = "type") val type: kotlin.String? = null,

    @SerialName(value = "requireAuth") val requireAuth: kotlin.Boolean? = null,

    @SerialName(value = "recipient") val recipient: UserBasic1? = null

)

