/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.MetaData
import org.openapitools.client.models.Profile

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param `data` 
 * @param metadata 
 */
@Serializable

data class RestProfilesGet200Response (

    @SerialName(value = "data") val `data`: kotlin.collections.List<Profile>? = null,

    @SerialName(value = "metadata") val metadata: MetaData? = null

)

