/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id Role ID
 * @param type Role type
 * @param rank Role rank
 * @param name Role name
 */
@Serializable

data class Role (

    /* Role ID */
    @SerialName(value = "id") val id: kotlin.Int? = null,

    /* Role type */
    @SerialName(value = "type") val type: kotlin.String? = null,

    /* Role rank */
    @SerialName(value = "rank") val rank: kotlin.Int? = null,

    /* Role name */
    @SerialName(value = "name") val name: kotlin.String? = null

)

