/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ScimMultiValue
import org.openapitools.client.models.ScimMultiValueMobile

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param userName 
 * @param schemas 
 * @param userType 
 * @param displayName 
 * @param userMustChange 
 * @param password 
 * @param notify 
 * @param phoneNumbers 
 * @param roles 
 */
@Serializable

data class ScimUsersPostRequest (

    @SerialName(value = "userName") @Required val userName: kotlin.String,

    @SerialName(value = "schemas") @Required val schemas: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "userType") val userType: kotlin.String? = null,

    @SerialName(value = "displayName") val displayName: kotlin.String? = null,

    @SerialName(value = "userMustChange") val userMustChange: kotlin.Boolean? = false,

    @SerialName(value = "password") val password: kotlin.String? = null,

    @SerialName(value = "notify") val notify: kotlin.Boolean? = false,

    @SerialName(value = "phoneNumbers") val phoneNumbers: kotlin.collections.List<ScimMultiValueMobile>? = null,

    @SerialName(value = "roles") val roles: kotlin.collections.List<ScimMultiValue>? = null

)

