/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Email
import org.openapitools.client.models.Folder
import org.openapitools.client.models.SearchMetadata

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class Search
 *
 * @param files List of files
 * @param folders List of folders
 * @param emails List of emails
 * @param id Unique search string
 * @param metadata 
 * @param fullTextSearch Whether full text search is enabled
 */
@Serializable

data class Search (

    /* List of files */
    @SerialName(value = "files") @Required val files: kotlin.collections.List<org.openapitools.client.infrastructure.OctetByteArray>,

    /* List of folders */
    @SerialName(value = "folders") @Required val folders: kotlin.collections.List<Folder>,

    /* List of emails */
    @SerialName(value = "emails") @Required val emails: kotlin.collections.List<Email>,

    /* Unique search string */
    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "metadata") val metadata: SearchMetadata? = null,

    /* Whether full text search is enabled */
    @SerialName(value = "fullTextSearch") val fullTextSearch: kotlin.Boolean? = null

)

