/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class SendRequestFile
 *
 * @param fileIds 
 * @param body 
 * @param selfCopy 
 */
@Serializable

data class SendRequestFilePost (

    @SerialName(value = "fileIds") @Required val fileIds: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "body") val body: kotlin.String? = null,

    @SerialName(value = "selfCopy") val selfCopy: kotlin.Boolean? = null

)

