/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class Sendfile
 *
 * @param to 
 * @param cc 
 * @param bcc 
 * @param files 
 * @param acl 
 * @param expire 
 * @param draft 
 * @param preview Indicates that email is a preview email
 * @param watermark The watermark on the preview email
 * @param secureBody 
 * @param selfCopy 
 * @param includeFingerprint 
 * @param parentEmailId 
 * @param isSelfReturnReceipt 
 * @param returnReceipts 
 * @param type Email type
 * @param uploading Indicates whether upload is still in progress. Prevents sending if is set to true.
 * @param body 
 * @param subject 
 * @param webFormId 
 * @param webFormFields 
 */
@Serializable

data class SendfilePost (

    @SerialName(value = "to") val to: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "cc") val cc: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "bcc") val bcc: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "files") val files: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "acl") val acl: SendfilePost.Acl? = null,

    @SerialName(value = "expire") val expire: kotlin.String? = null,

    @SerialName(value = "draft") val draft: kotlin.Boolean? = null,

    /* Indicates that email is a preview email */
    @SerialName(value = "preview") val preview: kotlin.Boolean? = null,

    /* The watermark on the preview email */
    @SerialName(value = "watermark") val watermark: kotlin.String? = null,

    @SerialName(value = "secureBody") val secureBody: kotlin.Boolean? = null,

    @SerialName(value = "selfCopy") val selfCopy: kotlin.Boolean? = null,

    @SerialName(value = "includeFingerprint") val includeFingerprint: kotlin.Boolean? = null,

    @SerialName(value = "parentEmailId") val parentEmailId: kotlin.Int? = null,

    @SerialName(value = "isSelfReturnReceipt") val isSelfReturnReceipt: kotlin.Boolean? = null,

    @SerialName(value = "returnReceipts") val returnReceipts: kotlin.collections.List<kotlin.String>? = null,

    /* Email type */
    @SerialName(value = "type") val type: SendfilePost.Type? = null,

    /* Indicates whether upload is still in progress. Prevents sending if is set to true. */
    @SerialName(value = "uploading") val uploading: kotlin.Boolean? = null,

    @SerialName(value = "body") val body: kotlin.String? = null,

    @SerialName(value = "subject") val subject: kotlin.String? = null,

    @SerialName(value = "webFormId") val webFormId: kotlin.String? = null,

    @SerialName(value = "webFormFields") val webFormFields: kotlin.collections.List<kotlin.String>? = null

) {

    /**
     * 
     *
     * Values: VERIFY_RECIPIENT,NO_AUTH,OTP,INTERNAL,ANYONE_AUTH
     */
    @Serializable
    enum class Acl(val value: kotlin.String) {
        @SerialName(value = "verify_recipient") VERIFY_RECIPIENT("verify_recipient"),
        @SerialName(value = "no_auth") NO_AUTH("no_auth"),
        @SerialName(value = "otp") OTP("otp"),
        @SerialName(value = "internal") INTERNAL("internal"),
        @SerialName(value = "anyone_auth") ANYONE_AUTH("anyone_auth");
    }
    /**
     * Email type
     *
     * Values: ORIGINAL,RESEND,FORWARD,REPLY
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "original") ORIGINAL("original"),
        @SerialName(value = "resend") RESEND("resend"),
        @SerialName(value = "forward") FORWARD("forward"),
        @SerialName(value = "reply") REPLY("reply");
    }
}

