/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param trackingAccess List of tracking access' email
 */
@Serializable

data class SendMailSettingPutRequest (

    /* List of tracking access' email */
    @SerialName(value = "trackingAccess") val trackingAccess: kotlin.collections.List<kotlin.String>? = null

)

