/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class Settings
 *
 * @param languageId Language ID in Setting
 * @param locationId ID of Location in Setting. User's personal default location for send file and uploads.
 * @param signature Email message Signature in Setting
 * @param mobileKeyStore Mobile Key Store of Setting
 */
@Serializable

data class SettingsPost (

    /* Language ID in Setting */
    @SerialName(value = "languageId") val languageId: kotlin.Int? = null,

    /* ID of Location in Setting. User's personal default location for send file and uploads. */
    @SerialName(value = "locationId") val locationId: kotlin.Int? = null,

    /* Email message Signature in Setting */
    @SerialName(value = "signature") val signature: kotlin.String? = null,

    /* Mobile Key Store of Setting */
    @SerialName(value = "mobileKeyStore") val mobileKeyStore: kotlin.String? = null

)

