/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class Settings
 *
 * @param languageId Language ID of the user the settings represent
 * @param locationId ID of Location in Setting. User's personal default location for send file and uploads
 * @param signature Email message Signature in Setting
 * @param storageUsed Storage the user used for the folders they own
 * @param storageQuota Storage allocated to the user for space in all the folders they own
 * @param mobileKeyStore Mobile Key Store of Setting
 * @param mobileNumber Mobile number in Setting
 * @param mobileNumberVerified Mobile number verified in Setting
 * @param links 
 */
@Serializable

data class Settings (

    /* Language ID of the user the settings represent */
    @SerialName(value = "languageId") val languageId: kotlin.Int? = null,

    /* ID of Location in Setting. User's personal default location for send file and uploads */
    @SerialName(value = "locationId") val locationId: kotlin.Int? = null,

    /* Email message Signature in Setting */
    @SerialName(value = "signature") val signature: kotlin.String? = null,

    /* Storage the user used for the folders they own */
    @SerialName(value = "storageUsed") val storageUsed: kotlin.Int? = null,

    /* Storage allocated to the user for space in all the folders they own */
    @SerialName(value = "storageQuota") val storageQuota: kotlin.Int? = null,

    /* Mobile Key Store of Setting */
    @SerialName(value = "mobileKeyStore") val mobileKeyStore: kotlin.String? = null,

    /* Mobile number in Setting */
    @SerialName(value = "mobileNumber") val mobileNumber: kotlin.String? = null,

    /* Mobile number verified in Setting */
    @SerialName(value = "mobileNumberVerified") val mobileNumberVerified: kotlin.Boolean? = null,

    @SerialName(value = "links") val links: kotlin.String? = null

)

