/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.UserBasic

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param members 
 * @param user 
 * @param active 
 */
@Serializable

data class SharedMailbox (

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "members") val members: kotlin.collections.List<UserBasic>? = null,

    @SerialName(value = "user") val user: UserBasic? = null,

    @SerialName(value = "active") val active: kotlin.Boolean? = null

)

