/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Permission
import org.openapitools.client.models.UserBasicInfo

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id Unique SourceContent identifier
 * @param name Name of source content
 * @param parentId Parent ID of Source
 * @param type Type of Object
 * @param wopiapp WOPI info for iOS app
 * @param created Time of Source created in UTC timestamp
 * @param modified Time of Source modified in UTC timestamp
 * @param status Status of the source
 * @param deleted Whether the file is deleted
 * @param path Shows object full path
 * @param userRoleId Current user role id (Explicit field. May be retrieved only if mentioned in \"with\" parameter)
 * @param creator 
 * @param permissions Current user's permissions (Explicit field. May be retrieved only if mentioned in \"with\" parameter)
 * @param rootId Root Id (Explicit field. May be retrieved only if mentioned in \"with\" parameter)
 * @param pathIds Path Ids (Explicit field. May be retrieved only if mentioned in \"with\" parameter)
 * @param sourceTypeId Source Type (Explicit field. May be retrieved only if mentioned in \"with\" parameter)
 * @param totalFilesCount Total Files Count (Explicit field. May be retrieved only if mentioned in \"with\" parameter)
 * @param totalFoldersCount Total Folders Count (Explicit field. May be retrieved only if mentioned in \"with\" parameter)
 * @param links 
 * @param isFavorite Indicates that Folder is marked as favorite for current user
 */
@Serializable

data class SourceFolder (

    /* Unique SourceContent identifier */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* Name of source content */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* Parent ID of Source */
    @SerialName(value = "parentId") @Required val parentId: kotlin.String,

    /* Type of Object */
    @SerialName(value = "type") @Required val type: kotlin.String,

    /* WOPI info for iOS app */
    @SerialName(value = "wopiapp") @Required val wopiapp: kotlin.Boolean,

    /* Time of Source created in UTC timestamp */
    @SerialName(value = "created") val created: kotlin.String? = null,

    /* Time of Source modified in UTC timestamp */
    @SerialName(value = "modified") val modified: kotlin.String? = null,

    /* Status of the source */
    @SerialName(value = "status") val status: kotlin.String? = null,

    /* Whether the file is deleted */
    @SerialName(value = "deleted") val deleted: kotlin.Boolean? = null,

    /* Shows object full path */
    @SerialName(value = "path") val path: kotlin.String? = null,

    /* Current user role id (Explicit field. May be retrieved only if mentioned in \"with\" parameter) */
    @SerialName(value = "userRoleId") val userRoleId: kotlin.Int? = null,

    @SerialName(value = "creator") val creator: UserBasicInfo? = null,

    /* Current user's permissions (Explicit field. May be retrieved only if mentioned in \"with\" parameter) */
    @SerialName(value = "permissions") val permissions: kotlin.collections.List<Permission>? = null,

    /* Root Id (Explicit field. May be retrieved only if mentioned in \"with\" parameter) */
    @SerialName(value = "rootId") val rootId: kotlin.String? = null,

    /* Path Ids (Explicit field. May be retrieved only if mentioned in \"with\" parameter) */
    @SerialName(value = "pathIds") val pathIds: kotlin.String? = null,

    /* Source Type (Explicit field. May be retrieved only if mentioned in \"with\" parameter) */
    @SerialName(value = "sourceTypeId") val sourceTypeId: kotlin.String? = null,

    /* Total Files Count (Explicit field. May be retrieved only if mentioned in \"with\" parameter) */
    @SerialName(value = "totalFilesCount") val totalFilesCount: kotlin.String? = null,

    /* Total Folders Count (Explicit field. May be retrieved only if mentioned in \"with\" parameter) */
    @SerialName(value = "totalFoldersCount") val totalFoldersCount: kotlin.String? = null,

    @SerialName(value = "links") val links: kotlin.String? = null,

    /* Indicates that Folder is marked as favorite for current user */
    @SerialName(value = "isFavorite") val isFavorite: kotlin.Boolean? = null

)

