/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param description 
 * @param sourceUrl 
 * @param name 
 * @param sourceTypeId 
 * @param pinned 
 * @param sourceByUser 
 * @param pinnedTime 
 * @param id 
 */
@Serializable

data class Source (

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "sourceUrl") val sourceUrl: kotlin.String? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "sourceTypeId") val sourceTypeId: kotlin.Int? = null,

    @SerialName(value = "pinned") val pinned: kotlin.Boolean? = null,

    @SerialName(value = "sourceByUser") val sourceByUser: kotlin.Boolean? = null,

    @SerialName(value = "pinnedTime") val pinnedTime: kotlin.String? = null,

    @SerialName(value = "id") val id: kotlin.String? = null

)

