/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.UserBasic

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param user 
 * @param userId 
 * @param objectId 
 * @param created 
 */
@Serializable

data class SyncedObject (

    @SerialName(value = "user") val user: UserBasic? = null,

    @SerialName(value = "userId") val userId: kotlin.String? = null,

    @SerialName(value = "objectId") val objectId: kotlin.String? = null,

    @SerialName(value = "created") val created: kotlin.String? = null

)

