/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class Task
 *
 * @param assigneeId User unique identifier
 * @param due Task due date
 * @param contents Task content
 * @param status 'D' = 'Defined', 'P' = 'In Progress', 'C' = 'Completed'
 */
@Serializable

data class TaskPut (

    /* User unique identifier */
    @SerialName(value = "assigneeId") @Required val assigneeId: kotlin.Int,

    /* Task due date */
    @SerialName(value = "due") @Required val due: java.time.LocalDate,

    /* Task content */
    @SerialName(value = "contents") @Required val contents: kotlin.String,

    /* 'D' = 'Defined', 'P' = 'In Progress', 'C' = 'Completed' */
    @SerialName(value = "status") val status: TaskPut.Status? = null

) {

    /**
     * 'D' = 'Defined', 'P' = 'In Progress', 'C' = 'Completed'
     *
     * Values: d,p,c
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "D") d("D"),
        @SerialName(value = "P") p("P"),
        @SerialName(value = "C") c("C");
    }
}

