/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class Tenant
 *
 * @param id Tenant unique identifier
 * @param name Tenant name
 * @param hostname Tenant Hostname
 * @param created Tenant Creation Date
 * @param state Status\\State of Tenant
 * @param customerId Customer ID
 * @param deploymentId Deployment ID
 * @param expires Usage Expiry
 * @param storageLimit Monthly storage usage limit
 * @param bandwidthLimit Monthly bandwidth usage limit
 * @param primaryAdminEmail Primary admin email ID
 * @param licensedUsersCount Number of licensed users
 * @param links 
 */
@Serializable

data class Tenant (

    /* Tenant unique identifier */
    @SerialName(value = "id") @Required val id: kotlin.Int,

    /* Tenant name */
    @SerialName(value = "name") @Required val name: kotlin.Int,

    /* Tenant Hostname */
    @SerialName(value = "hostname") val hostname: kotlin.String? = null,

    /* Tenant Creation Date */
    @SerialName(value = "created") val created: java.time.LocalDate? = null,

    /* Status\\State of Tenant */
    @SerialName(value = "state") val state: kotlin.String? = null,

    /* Customer ID */
    @SerialName(value = "customerId") val customerId: kotlin.String? = null,

    /* Deployment ID */
    @SerialName(value = "deploymentId") val deploymentId: kotlin.String? = null,

    /* Usage Expiry */
    @SerialName(value = "expires") val expires: java.time.LocalDate? = null,

    /* Monthly storage usage limit */
    @SerialName(value = "storageLimit") val storageLimit: kotlin.Int? = null,

    /* Monthly bandwidth usage limit */
    @SerialName(value = "bandwidthLimit") val bandwidthLimit: kotlin.Int? = null,

    /* Primary admin email ID */
    @SerialName(value = "primaryAdminEmail") val primaryAdminEmail: kotlin.String? = null,

    /* Number of licensed users */
    @SerialName(value = "licensedUsersCount") val licensedUsersCount: kotlin.Int? = null,

    @SerialName(value = "links") val links: kotlin.String? = null

)

