/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class Tray
 *
 * @param objectId Unique identifier of Object in Tray
 * @param parentId Object's parent Folder identifier
 * @param canMove Indicates whether an object can be moved
 * @param `object` 
 * @param links 
 */
@Serializable

data class Tray (

    /* Unique identifier of Object in Tray */
    @SerialName(value = "objectId") val objectId: kotlin.Int? = null,

    /* Object's parent Folder identifier */
    @SerialName(value = "parentId") val parentId: kotlin.Int? = null,

    /* Indicates whether an object can be moved */
    @SerialName(value = "canMove") val canMove: kotlin.Boolean? = null,

    @SerialName(value = "object") val `object`: org.openapitools.client.infrastructure.OctetByteArray? = null,

    @SerialName(value = "links") val links: kotlin.String? = null

)

