/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param uri 
 * @param totalSize 
 * @param location 
 * @param totalChunks 
 * @param completeOk 
 * @param uploadedChunks 
 * @param requestFileId 
 * @param timestamp 
 * @param backend 
 * @param userId 
 * @param clientModified 
 * @param lastTimestamp 
 * @param id Upload id
 * @param emailId 
 * @param uploadedSize 
 * @param replaceId 
 * @param finished 
 * @param svrUploadTime 
 * @param error 
 * @param clientName 
 * @param fileUrl 
 * @param clientCreated 
 */
@Serializable

data class Upload (

    @SerialName(value = "uri") val uri: kotlin.String? = null,

    @SerialName(value = "totalSize") val totalSize: kotlin.Int? = null,

    @SerialName(value = "location") val location: kotlin.String? = null,

    @SerialName(value = "totalChunks") val totalChunks: kotlin.Int? = null,

    @SerialName(value = "completeOk") val completeOk: kotlin.Int? = null,

    @SerialName(value = "uploadedChunks") val uploadedChunks: kotlin.Int? = null,

    @SerialName(value = "requestFileId") val requestFileId: kotlin.Int? = null,

    @SerialName(value = "timestamp") val timestamp: kotlin.String? = null,

    @SerialName(value = "backend") val backend: kotlin.String? = null,

    @SerialName(value = "userId") val userId: kotlin.String? = null,

    @SerialName(value = "clientModified") val clientModified: kotlin.String? = null,

    @SerialName(value = "lastTimestamp") val lastTimestamp: kotlin.String? = null,

    /* Upload id */
    @SerialName(value = "id") val id: kotlin.Int? = null,

    @SerialName(value = "emailId") val emailId: kotlin.Int? = null,

    @SerialName(value = "uploadedSize") val uploadedSize: kotlin.Int? = null,

    @SerialName(value = "replaceId") val replaceId: kotlin.String? = null,

    @SerialName(value = "finished") val finished: kotlin.Boolean? = null,

    @SerialName(value = "svrUploadTime") val svrUploadTime: kotlin.Int? = null,

    @SerialName(value = "error") val error: kotlin.String? = null,

    @SerialName(value = "clientName") val clientName: kotlin.String? = null,

    @SerialName(value = "fileUrl") val fileUrl: kotlin.String? = null,

    @SerialName(value = "clientCreated") val clientCreated: kotlin.String? = null

)

