/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class FileUpload
 *
 * @param filename File name
 * @param totalSize 
 * @param totalChunks Total chunks amount
 * @param clientCreated File creation date set from client
 * @param clientModified File modify date set from client
 * @param disableAutoVersion Indicates whether Client would like to save file as new version
 */
@Serializable

data class UploadPost (

    /* File name */
    @SerialName(value = "filename") @Required val filename: kotlin.String,

    @SerialName(value = "totalSize") val totalSize: kotlin.Int? = null,

    /* Total chunks amount */
    @SerialName(value = "totalChunks") val totalChunks: kotlin.Int? = null,

    /* File creation date set from client */
    @SerialName(value = "clientCreated") val clientCreated: java.time.LocalDate? = null,

    /* File modify date set from client */
    @SerialName(value = "clientModified") val clientModified: java.time.LocalDate? = null,

    /* Indicates whether Client would like to save file as new version */
    @SerialName(value = "disableAutoVersion") val disableAutoVersion: kotlin.Boolean? = null

)

