/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class UserMetadata
 *
 * @param name Metadata name
 * @param `value` Metadata value
 */
@Serializable

data class UserMetadata (

    /* Metadata name */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* Metadata value */
    @SerialName(value = "value") val `value`: kotlin.String? = null

)

