/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class UserMe
 *
 * @param suspended Indicates whether the user is suspended
 * @param name The name of the user
 * @param password The user's password
 * @param verified Indicates that the user is verified
 * @param deactivated The user deactivated flag
 */
@Serializable

data class UserMePut (

    /* Indicates whether the user is suspended */
    @SerialName(value = "suspended") val suspended: kotlin.Boolean? = null,

    /* The name of the user */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The user's password */
    @SerialName(value = "password") val password: kotlin.String? = null,

    /* Indicates that the user is verified */
    @SerialName(value = "verified") val verified: kotlin.Boolean? = null,

    /* The user deactivated flag */
    @SerialName(value = "deactivated") val deactivated: kotlin.Boolean? = null

)

