/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class User
 *
 * @param email The user's email
 * @param userTypeId The unique identifier of the user type
 * @param name The name of the user
 * @param password The user's password
 * @param verified Indicates that the user is verified
 * @param sendNotification Indicates whether send notification to user or not
 */
@Serializable

data class UserPost (

    /* The user's email */
    @SerialName(value = "email") @Required val email: kotlin.String,

    /* The unique identifier of the user type */
    @SerialName(value = "userTypeId") @Required val userTypeId: kotlin.Int,

    /* The name of the user */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The user's password */
    @SerialName(value = "password") val password: kotlin.String? = null,

    /* Indicates that the user is verified */
    @SerialName(value = "verified") val verified: kotlin.Boolean? = null,

    /* Indicates whether send notification to user or not */
    @SerialName(value = "sendNotification") val sendNotification: kotlin.Boolean? = null

)

