/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class UserTos
 *
 * @param accept accept
 * @param referral referral
 */
@Serializable

data class UserTosPost (

    /* accept */
    @SerialName(value = "accept") @Required val accept: kotlin.Boolean,

    /* referral */
    @SerialName(value = "referral") val referral: kotlin.String? = null

)

