/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.UserMetadata

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class UserMe
 *
 * @param id The unique identifier of the user
 * @param basedirId The unique identifier of the user's root kiteworks directory.      *                  Only folder creation is allowed on user's base directory.
 * @param email The user's email
 * @param mydirId The unique identifier of the user's mydir directory.      *                  mydir directory stores copies of files from email attachments and user's profile image.      *                  mydir is not visible to end users
 * @param name The name of the user
 * @param syncdirId Id of sync dir
 * @param created User creation date
 * @param userTypeId The unique identifier of the user type
 * @param `internal` Indicates that the user is an internal user
 * @param profileIcon User profile icon link
 * @param extDL Indicates that the user is External Distribution List
 * @param metadata List of user's metadata
 * @param adminRoleId 
 * @param links 
 * @param serviceName Service name
 */
@Serializable

data class UserMe (

    /* The unique identifier of the user */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* The unique identifier of the user's root kiteworks directory.      *                  Only folder creation is allowed on user's base directory. */
    @SerialName(value = "basedirId") @Required val basedirId: kotlin.String,

    /* The user's email */
    @SerialName(value = "email") @Required val email: kotlin.String,

    /* The unique identifier of the user's mydir directory.      *                  mydir directory stores copies of files from email attachments and user's profile image.      *                  mydir is not visible to end users */
    @SerialName(value = "mydirId") @Required val mydirId: kotlin.String,

    /* The name of the user */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* Id of sync dir */
    @SerialName(value = "syncdirId") @Required val syncdirId: kotlin.String,

    /* User creation date */
    @SerialName(value = "created") val created: java.time.LocalDate? = null,

    /* The unique identifier of the user type */
    @SerialName(value = "userTypeId") val userTypeId: kotlin.Int? = null,

    /* Indicates that the user is an internal user */
    @SerialName(value = "internal") val `internal`: kotlin.Boolean? = null,

    /* User profile icon link */
    @SerialName(value = "profileIcon") val profileIcon: kotlin.String? = null,

    /* Indicates that the user is External Distribution List */
    @SerialName(value = "extDL") val extDL: kotlin.Boolean? = null,

    /* List of user's metadata */
    @SerialName(value = "metadata") val metadata: kotlin.collections.List<UserMetadata>? = null,

    @SerialName(value = "adminRoleId") val adminRoleId: kotlin.Int? = null,

    @SerialName(value = "links") val links: kotlin.String? = null,

    /* Service name */
    @SerialName(value = "serviceName") val serviceName: kotlin.String? = null

)

