/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param type 
 * @param ids 
 */
@Serializable

data class UserMePinsPostRequest (

    @SerialName(value = "type") @Required val type: kotlin.String,

    @SerialName(value = "ids") @Required val ids: kotlin.collections.List<kotlin.String>

)

