/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class UserAdminRole
 *
 * @param userId User unique identifier
 * @param adminRole Admin role unique identifier. Possible values are: 1: System admin, 2: Application admin
 */
@Serializable

data class UserAdminRolePut (

    /* User unique identifier */
    @SerialName(value = "userId") val userId: kotlin.String? = null,

    /* Admin role unique identifier. Possible values are: 1: System admin, 2: Application admin */
    @SerialName(value = "adminRole") val adminRole: kotlin.String? = null

)

