/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class UserTfaTotpResetSecret
 *
 * @param password The user's password
 * @param otp OTP to verify the new secret
 */
@Serializable

data class UserTfaTotpResetSecretPut (

    /* The user's password */
    @SerialName(value = "password") @Required val password: kotlin.String,

    /* OTP to verify the new secret */
    @SerialName(value = "otp") val otp: kotlin.String? = null

)

