/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class UserDemoteToRestricted
 *
 * @param remoteWipe Remote wipe data on desktop and mobile devices
 * @param deleteUnsharedData 
 * @param retainData 
 * @param retainToUser Re-assign data to the user
 * @param retainPermissionToSharedData Retain permissions to shared data
 * @param withdrawRequestFiles 
 * @param withdrawFileLinks 
 */
@Serializable

data class UserDemoteToRestrictedPost (

    /* Remote wipe data on desktop and mobile devices */
    @SerialName(value = "remoteWipe") val remoteWipe: kotlin.Boolean? = null,

    @SerialName(value = "deleteUnsharedData") val deleteUnsharedData: kotlin.Boolean? = null,

    @SerialName(value = "retainData") val retainData: kotlin.Boolean? = null,

    /* Re-assign data to the user */
    @SerialName(value = "retainToUser") val retainToUser: kotlin.String? = null,

    /* Retain permissions to shared data */
    @SerialName(value = "retainPermissionToSharedData") val retainPermissionToSharedData: kotlin.Boolean? = null,

    @SerialName(value = "withdrawRequestFiles") val withdrawRequestFiles: kotlin.Boolean? = null,

    @SerialName(value = "withdrawFileLinks") val withdrawFileLinks: kotlin.Boolean? = null

)

