/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Class UserResetPassword
 *
 * @param link The password reset link
 * @param password Password
 */
@Serializable

data class UserResetPasswordPost (

    /* The password reset link */
    @SerialName(value = "link") @Required val link: kotlin.String,

    /* Password */
    @SerialName(value = "password") @Required val password: kotlin.String

)

