/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import org.openapitools.client.models.ScimUser
import org.openapitools.client.models.ScimUsers
import org.openapitools.client.models.ScimUsersPostRequest
import org.openapitools.client.models.ScimUsersPutRequest

import org.openapitools.client.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class ScimApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * 
     * Get SCIM resource types
     * @return void
     */
    open suspend fun restScimResourceTypesGet(): HttpResponse<Unit> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/rest/scim/ResourceTypes",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * Get a SCIM resource type
     * @param id The ID/URN of the schema
     * @return void
     */
    open suspend fun restScimResourceTypesIdGet(id: kotlin.String): HttpResponse<Unit> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/rest/scim/ResourceTypes/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * Get SCIM schemas
     * @return void
     */
    open suspend fun restScimSchemasGet(): HttpResponse<Unit> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/rest/scim/Schemas",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * Get a SCIM schema
     * @param id The ID/URN of the schema
     * @return void
     */
    open suspend fun restScimSchemasIdGet(id: kotlin.String): HttpResponse<Unit> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/rest/scim/Schemas/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get SCIM service provider config
     * Get SCIM service provider config
     * @return void
     */
    open suspend fun restScimServiceProviderConfigGet(): HttpResponse<Unit> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/rest/scim/ServiceProviderConfig",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * enum for parameter excludedAttributes
     */
    @Serializable
    enum class ExcludedAttributesRestScimUsersGet(val value: kotlin.String) {
        
        @SerialName(value = "meta")
        META("meta"),
        
        @SerialName(value = "userName")
        USER_NAME("userName"),
        
        @SerialName(value = "displayName")
        DISPLAY_NAME("displayName"),
        
        @SerialName(value = "userType")
        USER_TYPE("userType"),
        
        @SerialName(value = "preferredLanguage")
        PREFERRED_LANGUAGE("preferredLanguage"),
        
        @SerialName(value = "active")
        ACTIVE("active"),
        
        @SerialName(value = "emails")
        EMAILS("emails"),
        
        @SerialName(value = "phoneNumbers")
        PHONE_NUMBERS("phoneNumbers"),
        
        @SerialName(value = "photos")
        PHOTOS("photos"),
        
        @SerialName(value = "roles")
        ROLES("roles"),
        
        @SerialName(value = "meta.resourceType")
        META_PERIOD_RESOURCE_TYPE("meta.resourceType"),
        
        @SerialName(value = "meta.created")
        META_PERIOD_CREATED("meta.created"),
        
        @SerialName(value = "meta.location")
        META_PERIOD_LOCATION("meta.location"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:meta")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_META("urn:ietf:params:scim:schemas:core:2.0:User:meta"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:userName")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_USER_NAME("urn:ietf:params:scim:schemas:core:2.0:User:userName"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:displayName")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_DISPLAY_NAME("urn:ietf:params:scim:schemas:core:2.0:User:displayName"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:userType")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_USER_TYPE("urn:ietf:params:scim:schemas:core:2.0:User:userType"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:preferredLanguage")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_PREFERRED_LANGUAGE("urn:ietf:params:scim:schemas:core:2.0:User:preferredLanguage"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:active")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_ACTIVE("urn:ietf:params:scim:schemas:core:2.0:User:active"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:emails")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_EMAILS("urn:ietf:params:scim:schemas:core:2.0:User:emails"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:phoneNumbers")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_PHONE_NUMBERS("urn:ietf:params:scim:schemas:core:2.0:User:phoneNumbers"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:photos")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_PHOTOS("urn:ietf:params:scim:schemas:core:2.0:User:photos"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:roles")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_ROLES("urn:ietf:params:scim:schemas:core:2.0:User:roles"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:meta.resourceType")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_META_PERIOD_RESOURCE_TYPE("urn:ietf:params:scim:schemas:core:2.0:User:meta.resourceType"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:meta.created")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_META_PERIOD_CREATED("urn:ietf:params:scim:schemas:core:2.0:User:meta.created"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:meta.location")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_META_PERIOD_LOCATION("urn:ietf:params:scim:schemas:core:2.0:User:meta.location")
        
    }


    /**
     * enum for parameter attributes
     */
    @Serializable
    enum class AttributesRestScimUsersGet(val value: kotlin.String) {
        
        @SerialName(value = "id")
        ID("id"),
        
        @SerialName(value = "meta")
        META("meta"),
        
        @SerialName(value = "userName")
        USER_NAME("userName"),
        
        @SerialName(value = "displayName")
        DISPLAY_NAME("displayName"),
        
        @SerialName(value = "userType")
        USER_TYPE("userType"),
        
        @SerialName(value = "preferredLanguage")
        PREFERRED_LANGUAGE("preferredLanguage"),
        
        @SerialName(value = "active")
        ACTIVE("active"),
        
        @SerialName(value = "emails")
        EMAILS("emails"),
        
        @SerialName(value = "phoneNumbers")
        PHONE_NUMBERS("phoneNumbers"),
        
        @SerialName(value = "photos")
        PHOTOS("photos"),
        
        @SerialName(value = "roles")
        ROLES("roles"),
        
        @SerialName(value = "meta.resourceType")
        META_PERIOD_RESOURCE_TYPE("meta.resourceType"),
        
        @SerialName(value = "meta.created")
        META_PERIOD_CREATED("meta.created"),
        
        @SerialName(value = "meta.location")
        META_PERIOD_LOCATION("meta.location"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:id")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_ID("urn:ietf:params:scim:schemas:core:2.0:User:id"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:meta")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_META("urn:ietf:params:scim:schemas:core:2.0:User:meta"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:userName")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_USER_NAME("urn:ietf:params:scim:schemas:core:2.0:User:userName"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:displayName")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_DISPLAY_NAME("urn:ietf:params:scim:schemas:core:2.0:User:displayName"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:userType")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_USER_TYPE("urn:ietf:params:scim:schemas:core:2.0:User:userType"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:preferredLanguage")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_PREFERRED_LANGUAGE("urn:ietf:params:scim:schemas:core:2.0:User:preferredLanguage"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:active")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_ACTIVE("urn:ietf:params:scim:schemas:core:2.0:User:active"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:emails")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_EMAILS("urn:ietf:params:scim:schemas:core:2.0:User:emails"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:phoneNumbers")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_PHONE_NUMBERS("urn:ietf:params:scim:schemas:core:2.0:User:phoneNumbers"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:photos")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_PHOTOS("urn:ietf:params:scim:schemas:core:2.0:User:photos"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:roles")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_ROLES("urn:ietf:params:scim:schemas:core:2.0:User:roles"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:meta.resourceType")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_META_PERIOD_RESOURCE_TYPE("urn:ietf:params:scim:schemas:core:2.0:User:meta.resourceType"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:meta.created")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_META_PERIOD_CREATED("urn:ietf:params:scim:schemas:core:2.0:User:meta.created"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:meta.location")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_META_PERIOD_LOCATION("urn:ietf:params:scim:schemas:core:2.0:User:meta.location")
        
    }

    /**
     * Retrieve users
     * Retrieve users
     * @param filter  (optional)
     * @param sortOrder  (optional)
     * @param count  (optional)
     * @param startIndex  (optional)
     * @param sortBy  (optional)
     * @param excludedAttributes  (optional)
     * @param attributes  (optional)
     * @return ScimUsers
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun restScimUsersGet(filter: kotlin.String? = null, sortOrder: kotlin.String? = null, count: kotlin.Int? = null, startIndex: kotlin.Int? = null, sortBy: kotlin.String? = null, excludedAttributes: kotlin.collections.List<ExcludedAttributesRestScimUsersGet>? = null, attributes: kotlin.collections.List<AttributesRestScimUsersGet>? = null): HttpResponse<ScimUsers> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        filter?.apply { localVariableQuery["filter"] = listOf("$filter") }
        sortOrder?.apply { localVariableQuery["sortOrder"] = listOf("$sortOrder") }
        count?.apply { localVariableQuery["count"] = listOf("$count") }
        startIndex?.apply { localVariableQuery["startIndex"] = listOf("$startIndex") }
        sortBy?.apply { localVariableQuery["sortBy"] = listOf("$sortBy") }
        excludedAttributes?.apply { localVariableQuery["excludedAttributes"] = toMultiValue(this, "csv") }
        attributes?.apply { localVariableQuery["attributes"] = toMultiValue(this, "csv") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/rest/scim/users",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Delete single user
     * Delete single user
     * @param id The ID of the entity
     * @param remoteWipe  (optional)
     * @param retainData  (optional)
     * @param retainPermissionToSharedData  (optional)
     * @param deleteUnsharedData  (optional)
     * @param retainToUser  (optional)
     * @return void
     */
    open suspend fun restScimUsersIdDelete(id: kotlin.String, remoteWipe: kotlin.Boolean? = null, retainData: kotlin.Boolean? = null, retainPermissionToSharedData: kotlin.Boolean? = null, deleteUnsharedData: kotlin.Boolean? = null, retainToUser: kotlin.String? = null): HttpResponse<Unit> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        remoteWipe?.apply { localVariableQuery["remoteWipe"] = listOf("$remoteWipe") }
        retainData?.apply { localVariableQuery["retainData"] = listOf("$retainData") }
        retainPermissionToSharedData?.apply { localVariableQuery["retainPermissionToSharedData"] = listOf("$retainPermissionToSharedData") }
        deleteUnsharedData?.apply { localVariableQuery["deleteUnsharedData"] = listOf("$deleteUnsharedData") }
        retainToUser?.apply { localVariableQuery["retainToUser"] = listOf("$retainToUser") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/rest/scim/users/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * enum for parameter attributes
     */
    @Serializable
    enum class AttributesRestScimUsersIdGet(val value: kotlin.String) {
        
        @SerialName(value = "id")
        ID("id"),
        
        @SerialName(value = "meta")
        META("meta"),
        
        @SerialName(value = "userName")
        USER_NAME("userName"),
        
        @SerialName(value = "displayName")
        DISPLAY_NAME("displayName"),
        
        @SerialName(value = "userType")
        USER_TYPE("userType"),
        
        @SerialName(value = "preferredLanguage")
        PREFERRED_LANGUAGE("preferredLanguage"),
        
        @SerialName(value = "active")
        ACTIVE("active"),
        
        @SerialName(value = "emails")
        EMAILS("emails"),
        
        @SerialName(value = "phoneNumbers")
        PHONE_NUMBERS("phoneNumbers"),
        
        @SerialName(value = "photos")
        PHOTOS("photos"),
        
        @SerialName(value = "roles")
        ROLES("roles"),
        
        @SerialName(value = "meta.resourceType")
        META_PERIOD_RESOURCE_TYPE("meta.resourceType"),
        
        @SerialName(value = "meta.created")
        META_PERIOD_CREATED("meta.created"),
        
        @SerialName(value = "meta.location")
        META_PERIOD_LOCATION("meta.location"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:id")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_ID("urn:ietf:params:scim:schemas:core:2.0:User:id"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:meta")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_META("urn:ietf:params:scim:schemas:core:2.0:User:meta"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:userName")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_USER_NAME("urn:ietf:params:scim:schemas:core:2.0:User:userName"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:displayName")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_DISPLAY_NAME("urn:ietf:params:scim:schemas:core:2.0:User:displayName"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:userType")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_USER_TYPE("urn:ietf:params:scim:schemas:core:2.0:User:userType"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:preferredLanguage")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_PREFERRED_LANGUAGE("urn:ietf:params:scim:schemas:core:2.0:User:preferredLanguage"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:active")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_ACTIVE("urn:ietf:params:scim:schemas:core:2.0:User:active"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:emails")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_EMAILS("urn:ietf:params:scim:schemas:core:2.0:User:emails"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:phoneNumbers")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_PHONE_NUMBERS("urn:ietf:params:scim:schemas:core:2.0:User:phoneNumbers"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:photos")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_PHOTOS("urn:ietf:params:scim:schemas:core:2.0:User:photos"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:roles")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_ROLES("urn:ietf:params:scim:schemas:core:2.0:User:roles"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:meta.resourceType")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_META_PERIOD_RESOURCE_TYPE("urn:ietf:params:scim:schemas:core:2.0:User:meta.resourceType"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:meta.created")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_META_PERIOD_CREATED("urn:ietf:params:scim:schemas:core:2.0:User:meta.created"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:meta.location")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_META_PERIOD_LOCATION("urn:ietf:params:scim:schemas:core:2.0:User:meta.location")
        
    }


    /**
     * enum for parameter excludedAttributes
     */
    @Serializable
    enum class ExcludedAttributesRestScimUsersIdGet(val value: kotlin.String) {
        
        @SerialName(value = "meta")
        META("meta"),
        
        @SerialName(value = "userName")
        USER_NAME("userName"),
        
        @SerialName(value = "displayName")
        DISPLAY_NAME("displayName"),
        
        @SerialName(value = "userType")
        USER_TYPE("userType"),
        
        @SerialName(value = "preferredLanguage")
        PREFERRED_LANGUAGE("preferredLanguage"),
        
        @SerialName(value = "active")
        ACTIVE("active"),
        
        @SerialName(value = "emails")
        EMAILS("emails"),
        
        @SerialName(value = "phoneNumbers")
        PHONE_NUMBERS("phoneNumbers"),
        
        @SerialName(value = "photos")
        PHOTOS("photos"),
        
        @SerialName(value = "roles")
        ROLES("roles"),
        
        @SerialName(value = "meta.resourceType")
        META_PERIOD_RESOURCE_TYPE("meta.resourceType"),
        
        @SerialName(value = "meta.created")
        META_PERIOD_CREATED("meta.created"),
        
        @SerialName(value = "meta.location")
        META_PERIOD_LOCATION("meta.location"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:meta")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_META("urn:ietf:params:scim:schemas:core:2.0:User:meta"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:userName")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_USER_NAME("urn:ietf:params:scim:schemas:core:2.0:User:userName"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:displayName")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_DISPLAY_NAME("urn:ietf:params:scim:schemas:core:2.0:User:displayName"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:userType")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_USER_TYPE("urn:ietf:params:scim:schemas:core:2.0:User:userType"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:preferredLanguage")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_PREFERRED_LANGUAGE("urn:ietf:params:scim:schemas:core:2.0:User:preferredLanguage"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:active")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_ACTIVE("urn:ietf:params:scim:schemas:core:2.0:User:active"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:emails")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_EMAILS("urn:ietf:params:scim:schemas:core:2.0:User:emails"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:phoneNumbers")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_PHONE_NUMBERS("urn:ietf:params:scim:schemas:core:2.0:User:phoneNumbers"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:photos")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_PHOTOS("urn:ietf:params:scim:schemas:core:2.0:User:photos"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:roles")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_ROLES("urn:ietf:params:scim:schemas:core:2.0:User:roles"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:meta.resourceType")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_META_PERIOD_RESOURCE_TYPE("urn:ietf:params:scim:schemas:core:2.0:User:meta.resourceType"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:meta.created")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_META_PERIOD_CREATED("urn:ietf:params:scim:schemas:core:2.0:User:meta.created"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:meta.location")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_META_PERIOD_LOCATION("urn:ietf:params:scim:schemas:core:2.0:User:meta.location")
        
    }

    /**
     * Get a user specified by the id
     * Get a user specified by the id
     * @param id The ID of the entity
     * @param attributes  (optional)
     * @param excludedAttributes  (optional)
     * @return ScimUser
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun restScimUsersIdGet(id: kotlin.String, attributes: kotlin.collections.List<AttributesRestScimUsersIdGet>? = null, excludedAttributes: kotlin.collections.List<ExcludedAttributesRestScimUsersIdGet>? = null): HttpResponse<ScimUser> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        attributes?.apply { localVariableQuery["attributes"] = toMultiValue(this, "csv") }
        excludedAttributes?.apply { localVariableQuery["excludedAttributes"] = toMultiValue(this, "csv") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/rest/scim/users/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * 
     * Update a user specified by the id
     * @param id The ID of the entity
     * @param body 
     * @return ScimUser
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun restScimUsersIdPut(id: kotlin.String, body: ScimUsersPutRequest): HttpResponse<ScimUser> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PUT,
            "/rest/scim/users/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }




    /**
     * enum for parameter attributes
     */
    @Serializable
    enum class AttributesRestScimUsersPost(val value: kotlin.String) {
        
        @SerialName(value = "id")
        ID("id"),
        
        @SerialName(value = "meta")
        META("meta"),
        
        @SerialName(value = "userName")
        USER_NAME("userName"),
        
        @SerialName(value = "displayName")
        DISPLAY_NAME("displayName"),
        
        @SerialName(value = "userType")
        USER_TYPE("userType"),
        
        @SerialName(value = "preferredLanguage")
        PREFERRED_LANGUAGE("preferredLanguage"),
        
        @SerialName(value = "active")
        ACTIVE("active"),
        
        @SerialName(value = "emails")
        EMAILS("emails"),
        
        @SerialName(value = "phoneNumbers")
        PHONE_NUMBERS("phoneNumbers"),
        
        @SerialName(value = "photos")
        PHOTOS("photos"),
        
        @SerialName(value = "roles")
        ROLES("roles"),
        
        @SerialName(value = "meta.resourceType")
        META_PERIOD_RESOURCE_TYPE("meta.resourceType"),
        
        @SerialName(value = "meta.created")
        META_PERIOD_CREATED("meta.created"),
        
        @SerialName(value = "meta.location")
        META_PERIOD_LOCATION("meta.location"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:id")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_ID("urn:ietf:params:scim:schemas:core:2.0:User:id"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:meta")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_META("urn:ietf:params:scim:schemas:core:2.0:User:meta"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:userName")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_USER_NAME("urn:ietf:params:scim:schemas:core:2.0:User:userName"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:displayName")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_DISPLAY_NAME("urn:ietf:params:scim:schemas:core:2.0:User:displayName"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:userType")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_USER_TYPE("urn:ietf:params:scim:schemas:core:2.0:User:userType"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:preferredLanguage")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_PREFERRED_LANGUAGE("urn:ietf:params:scim:schemas:core:2.0:User:preferredLanguage"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:active")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_ACTIVE("urn:ietf:params:scim:schemas:core:2.0:User:active"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:emails")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_EMAILS("urn:ietf:params:scim:schemas:core:2.0:User:emails"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:phoneNumbers")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_PHONE_NUMBERS("urn:ietf:params:scim:schemas:core:2.0:User:phoneNumbers"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:photos")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_PHOTOS("urn:ietf:params:scim:schemas:core:2.0:User:photos"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:roles")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_ROLES("urn:ietf:params:scim:schemas:core:2.0:User:roles"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:meta.resourceType")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_META_PERIOD_RESOURCE_TYPE("urn:ietf:params:scim:schemas:core:2.0:User:meta.resourceType"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:meta.created")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_META_PERIOD_CREATED("urn:ietf:params:scim:schemas:core:2.0:User:meta.created"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:meta.location")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_META_PERIOD_LOCATION("urn:ietf:params:scim:schemas:core:2.0:User:meta.location")
        
    }


    /**
     * enum for parameter excludedAttributes
     */
    @Serializable
    enum class ExcludedAttributesRestScimUsersPost(val value: kotlin.String) {
        
        @SerialName(value = "meta")
        META("meta"),
        
        @SerialName(value = "userName")
        USER_NAME("userName"),
        
        @SerialName(value = "displayName")
        DISPLAY_NAME("displayName"),
        
        @SerialName(value = "userType")
        USER_TYPE("userType"),
        
        @SerialName(value = "preferredLanguage")
        PREFERRED_LANGUAGE("preferredLanguage"),
        
        @SerialName(value = "active")
        ACTIVE("active"),
        
        @SerialName(value = "emails")
        EMAILS("emails"),
        
        @SerialName(value = "phoneNumbers")
        PHONE_NUMBERS("phoneNumbers"),
        
        @SerialName(value = "photos")
        PHOTOS("photos"),
        
        @SerialName(value = "roles")
        ROLES("roles"),
        
        @SerialName(value = "meta.resourceType")
        META_PERIOD_RESOURCE_TYPE("meta.resourceType"),
        
        @SerialName(value = "meta.created")
        META_PERIOD_CREATED("meta.created"),
        
        @SerialName(value = "meta.location")
        META_PERIOD_LOCATION("meta.location"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:meta")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_META("urn:ietf:params:scim:schemas:core:2.0:User:meta"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:userName")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_USER_NAME("urn:ietf:params:scim:schemas:core:2.0:User:userName"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:displayName")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_DISPLAY_NAME("urn:ietf:params:scim:schemas:core:2.0:User:displayName"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:userType")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_USER_TYPE("urn:ietf:params:scim:schemas:core:2.0:User:userType"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:preferredLanguage")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_PREFERRED_LANGUAGE("urn:ietf:params:scim:schemas:core:2.0:User:preferredLanguage"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:active")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_ACTIVE("urn:ietf:params:scim:schemas:core:2.0:User:active"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:emails")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_EMAILS("urn:ietf:params:scim:schemas:core:2.0:User:emails"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:phoneNumbers")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_PHONE_NUMBERS("urn:ietf:params:scim:schemas:core:2.0:User:phoneNumbers"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:photos")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_PHOTOS("urn:ietf:params:scim:schemas:core:2.0:User:photos"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:roles")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_ROLES("urn:ietf:params:scim:schemas:core:2.0:User:roles"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:meta.resourceType")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_META_PERIOD_RESOURCE_TYPE("urn:ietf:params:scim:schemas:core:2.0:User:meta.resourceType"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:meta.created")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_META_PERIOD_CREATED("urn:ietf:params:scim:schemas:core:2.0:User:meta.created"),
        
        @SerialName(value = "urn:ietf:params:scim:schemas:core:2.0:User:meta.location")
        URN_COLON_IETF_COLON_PARAMS_COLON_SCIM_COLON_SCHEMAS_COLON_CORE_COLON2_PERIOD0_COLON_USER_COLON_META_PERIOD_LOCATION("urn:ietf:params:scim:schemas:core:2.0:User:meta.location")
        
    }

    /**
     * Create single user
     * Create single user
     * @param body 
     * @param attributes  (optional)
     * @param excludedAttributes  (optional)
     * @return ScimUser
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun restScimUsersPost(body: ScimUsersPostRequest, attributes: kotlin.collections.List<AttributesRestScimUsersPost>? = null, excludedAttributes: kotlin.collections.List<ExcludedAttributesRestScimUsersPost>? = null): HttpResponse<ScimUser> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        attributes?.apply { localVariableQuery["attributes"] = toMultiValue(this, "csv") }
        excludedAttributes?.apply { localVariableQuery["excludedAttributes"] = toMultiValue(this, "csv") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/rest/scim/users",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



}
