/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import org.openapitools.client.models.Search
import org.openapitools.client.models.SearchResult
import org.openapitools.client.models.SearchSharePointSitesResult

import org.openapitools.client.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class SearchApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * Search api
     * search files/folders/emails
     * @param includeContent indicate it is full_text_search or database search
     * @param searchType 
     * @param sharedMailboxId  (optional)
     * @param createdColonGt email/file/folder creation date &gt; specified parameter (optional)
     * @param subject  (optional)
     * @param fileSizeColonGte file size &gt;&#x3D; specified value (optional)
     * @param fileSizeColonGt file size &gt; specified value (optional)
     * @param createdColonLte email/file/folder &lt;&#x3D; specified parameter (optional)
     * @param fileSizeColonLt file size &lt; specified value (optional)
     * @param created email/file/folder creation date &#x3D; specified parameter (optional)
     * @param modified email/file/folder modified date &#x3D; specified value (optional)
     * @param modifiedColonGt email/file/folder modified date &gt; specified value (optional)
     * @param limit  (optional)
     * @param recipientId recipient id or email (optional)
     * @param modifiedColonLt email/file/folder modified date &lt; specified value (optional)
     * @param createdColonGte email/file/folder creation date &gt;&#x3D; specified parameter (optional)
     * @param createdColonLt email/file/folder creation date &lt; specified parameter (optional)
     * @param path  (optional)
     * @param flsOnly only include files/folders shared to me (optional)
     * @param objectId search within folder id (optional)
     * @param spellCheck To get suggestions of searching keyword (optional)
     * @param fileSize file size &#x3D; specified parameter (optional)
     * @param user  (optional)
     * @param query  (optional)
     * @param fileType  (optional)
     * @param bucket  (optional)
     * @param fileName  (optional)
     * @param folderName  (optional)
     * @param fileSizeColonLte file size &lt;&#x3D; specified value (optional)
     * @param modifiedColonGte email/file/folder modified date &gt;&#x3D; specified value (optional)
     * @param orderType  (optional)
     * @param senderId sender id or email (optional)
     * @param offset  (optional)
     * @param nameOnly indicate when searching file/only with name only option (optional)
     * @param orderBy  (optional)
     * @param modifiedColonLte email/file/folder modified date &lt;&#x3D; specified value (optional)
     * @return SearchResult
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun restQueryGet(includeContent: kotlin.Boolean, searchType: kotlin.collections.List<kotlin.String>, sharedMailboxId: kotlin.String? = null, createdColonGt: kotlin.String? = null, subject: kotlin.String? = null, fileSizeColonGte: kotlin.String? = null, fileSizeColonGt: kotlin.Int? = null, createdColonLte: kotlin.String? = null, fileSizeColonLt: kotlin.String? = null, created: kotlin.String? = null, modified: kotlin.String? = null, modifiedColonGt: kotlin.String? = null, limit: kotlin.Int? = null, recipientId: kotlin.String? = null, modifiedColonLt: kotlin.String? = null, createdColonGte: kotlin.String? = null, createdColonLt: kotlin.String? = null, path: kotlin.String? = null, flsOnly: kotlin.Boolean? = null, objectId: kotlin.String? = null, spellCheck: kotlin.Boolean? = null, fileSize: kotlin.Int? = null, user: kotlin.String? = null, query: kotlin.String? = null, fileType: kotlin.collections.List<kotlin.String>? = null, bucket: kotlin.String? = null, fileName: kotlin.String? = null, folderName: kotlin.String? = null, fileSizeColonLte: kotlin.String? = null, modifiedColonGte: kotlin.String? = null, orderType: kotlin.String? = null, senderId: kotlin.String? = null, offset: kotlin.Int? = null, nameOnly: kotlin.Boolean? = null, orderBy: kotlin.String? = null, modifiedColonLte: kotlin.String? = null): HttpResponse<SearchResult> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        includeContent?.apply { localVariableQuery["includeContent"] = listOf("$includeContent") }
        sharedMailboxId?.apply { localVariableQuery["sharedMailboxId"] = listOf("$sharedMailboxId") }
        createdColonGt?.apply { localVariableQuery["created:gt"] = listOf("$createdColonGt") }
        subject?.apply { localVariableQuery["subject"] = listOf("$subject") }
        fileSizeColonGte?.apply { localVariableQuery["fileSize:gte"] = listOf("$fileSizeColonGte") }
        fileSizeColonGt?.apply { localVariableQuery["fileSize:gt"] = listOf("$fileSizeColonGt") }
        createdColonLte?.apply { localVariableQuery["created:lte"] = listOf("$createdColonLte") }
        fileSizeColonLt?.apply { localVariableQuery["fileSize:lt"] = listOf("$fileSizeColonLt") }
        created?.apply { localVariableQuery["created"] = listOf("$created") }
        modified?.apply { localVariableQuery["modified"] = listOf("$modified") }
        modifiedColonGt?.apply { localVariableQuery["modified:gt"] = listOf("$modifiedColonGt") }
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        recipientId?.apply { localVariableQuery["recipientId"] = listOf("$recipientId") }
        modifiedColonLt?.apply { localVariableQuery["modified:lt"] = listOf("$modifiedColonLt") }
        createdColonGte?.apply { localVariableQuery["created:gte"] = listOf("$createdColonGte") }
        createdColonLt?.apply { localVariableQuery["created:lt"] = listOf("$createdColonLt") }
        path?.apply { localVariableQuery["path"] = listOf("$path") }
        flsOnly?.apply { localVariableQuery["flsOnly"] = listOf("$flsOnly") }
        objectId?.apply { localVariableQuery["objectId"] = listOf("$objectId") }
        spellCheck?.apply { localVariableQuery["spellCheck"] = listOf("$spellCheck") }
        fileSize?.apply { localVariableQuery["fileSize"] = listOf("$fileSize") }
        user?.apply { localVariableQuery["user"] = listOf("$user") }
        query?.apply { localVariableQuery["query"] = listOf("$query") }
        searchType?.apply { localVariableQuery["searchType"] = toMultiValue(this, "csv") }
        fileType?.apply { localVariableQuery["fileType"] = toMultiValue(this, "csv") }
        bucket?.apply { localVariableQuery["bucket"] = listOf("$bucket") }
        fileName?.apply { localVariableQuery["fileName"] = listOf("$fileName") }
        folderName?.apply { localVariableQuery["folderName"] = listOf("$folderName") }
        fileSizeColonLte?.apply { localVariableQuery["fileSize:lte"] = listOf("$fileSizeColonLte") }
        modifiedColonGte?.apply { localVariableQuery["modified:gte"] = listOf("$modifiedColonGte") }
        orderType?.apply { localVariableQuery["orderType"] = listOf("$orderType") }
        senderId?.apply { localVariableQuery["senderId"] = listOf("$senderId") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        nameOnly?.apply { localVariableQuery["nameOnly"] = listOf("$nameOnly") }
        orderBy?.apply { localVariableQuery["orderBy"] = listOf("$orderBy") }
        modifiedColonLte?.apply { localVariableQuery["modified:lte"] = listOf("$modifiedColonLte") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/rest/query",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Return lists of files/folders/emails from search results
     * Return lists of files/folders/emails from search results
     * @param objectId Id of folder to search (optional)
     * @param content Search by content (optional)
     * @param contentColonContains Search by content. Search for result that contains specified characters in this parameter. (optional)
     * @param contentColonStartswith  (optional)
     * @param description Search by description (optional)
     * @param descriptionColonContains Search by description. Search for result that contains specified characters in this parameter. (optional)
     * @param descriptionColonStartswith  (optional)
     * @param user Search by user (optional)
     * @param modified Search by modified date (optional)
     * @param modifiedColonGt Search by modified date. Search for result that has this parameter value greater than specified. (optional)
     * @param modifiedColonGte Search by modified date. Search for result that has this parameter value greater or equal to the specified. (optional)
     * @param modifiedColonLt Search by modified date. Search for result that has this parameter value less than specified. (optional)
     * @param modifiedColonLte Search by modified date. Search for result that has this parameter value less or equal to the specified. (optional)
     * @param created Search by created date (optional)
     * @param createdColonGt Search by created date. Search for result that has this parameter value greater than specified. (optional)
     * @param createdColonGte Search by created date. Search for result that has this parameter value greater or equal to the specified. (optional)
     * @param createdColonLt Search by created date. Search for result that has this parameter value less than specified. (optional)
     * @param createdColonLte Search by created date. Search for result that has this parameter value less or equal to the specified. (optional)
     * @param locked Search by lock status (optional)
     * @param lockedColonGt Search by lock status. Search for result that has this parameter value greater than specified. (optional)
     * @param lockedColonGte Search by lock status. Search for result that has this parameter value greater or equal to the specified. (optional)
     * @param lockedColonLt Search by lock status. Search for result that has this parameter value less than specified. (optional)
     * @param lockedColonLte Search by lock status. Search for result that has this parameter value less or equal to the specified. (optional)
     * @param filesize Search by file size (optional)
     * @param filesizeColonGt Search by file size. Search for result that has this parameter value greater than specified. (optional)
     * @param filesizeColonGte Search by file size. Search for result that has this parameter value greater or equal to the specified. (optional)
     * @param filesizeColonLt Search by file size. Search for result that has this parameter value less than specified. (optional)
     * @param filesizeColonLte Search by file size. Search for result that has this parameter value less or equal to the specified. (optional)
     * @param fileType Search by file type (optional)
     * @param emailType Search by email type (optional)
     * @param path Search files/folders by path. If this is specified, other search criteria is no longer valid. (optional)
     * @param pathColonContains Search files/folders by path. If this is specified, other search criteria is no longer valid.. Search for result that contains specified characters in this parameter. (optional)
     * @param searchType Search type: f(files), d(directories), m(mails) or  k(kitepoint) (optional)
     * @param searchFilter Search all or only shared folders (optional)
     * @param flsOnly Search by file shared to me (optional)
     * @param sharedMailboxId Id of shared mailbox to search (optional)
     * @param orderBy Sorting options (optional)
     * @param offset Offset (optional)
     * @param limit Limit (optional)
     * @param with With parameters (optional)
     * @param mode Response mode (optional)
     * @return Search
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun restSearchGet(objectId: kotlin.String? = null, content: kotlin.String? = null, contentColonContains: kotlin.String? = null, contentColonStartswith: kotlin.String? = null, description: kotlin.String? = null, descriptionColonContains: kotlin.String? = null, descriptionColonStartswith: kotlin.String? = null, user: kotlin.String? = null, modified: kotlin.String? = null, modifiedColonGt: kotlin.String? = null, modifiedColonGte: kotlin.String? = null, modifiedColonLt: kotlin.String? = null, modifiedColonLte: kotlin.String? = null, created: kotlin.String? = null, createdColonGt: kotlin.String? = null, createdColonGte: kotlin.String? = null, createdColonLt: kotlin.String? = null, createdColonLte: kotlin.String? = null, locked: kotlin.Int? = null, lockedColonGt: kotlin.Int? = null, lockedColonGte: kotlin.Int? = null, lockedColonLt: kotlin.Int? = null, lockedColonLte: kotlin.Int? = null, filesize: kotlin.Int? = null, filesizeColonGt: kotlin.Int? = null, filesizeColonGte: kotlin.Int? = null, filesizeColonLt: kotlin.Int? = null, filesizeColonLte: kotlin.Int? = null, fileType: kotlin.collections.List<kotlin.String>? = null, emailType: kotlin.collections.List<kotlin.String>? = null, path: kotlin.String? = null, pathColonContains: kotlin.String? = null, searchType: kotlin.collections.List<kotlin.String>? = null, searchFilter: kotlin.String? = null, flsOnly: kotlin.Boolean? = null, sharedMailboxId: kotlin.Int? = null, orderBy: kotlin.collections.List<kotlin.String>? = null, offset: kotlin.Int? = null, limit: kotlin.Int? = null, with: kotlin.String? = null, mode: kotlin.String? = null): HttpResponse<Search> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        objectId?.apply { localVariableQuery["objectId"] = listOf("$objectId") }
        content?.apply { localVariableQuery["content"] = listOf("$content") }
        contentColonContains?.apply { localVariableQuery["content:contains"] = listOf("$contentColonContains") }
        contentColonStartswith?.apply { localVariableQuery["content:startswith"] = listOf("$contentColonStartswith") }
        description?.apply { localVariableQuery["description"] = listOf("$description") }
        descriptionColonContains?.apply { localVariableQuery["description:contains"] = listOf("$descriptionColonContains") }
        descriptionColonStartswith?.apply { localVariableQuery["description:startswith"] = listOf("$descriptionColonStartswith") }
        user?.apply { localVariableQuery["user"] = listOf("$user") }
        modified?.apply { localVariableQuery["modified"] = listOf("$modified") }
        modifiedColonGt?.apply { localVariableQuery["modified:gt"] = listOf("$modifiedColonGt") }
        modifiedColonGte?.apply { localVariableQuery["modified:gte"] = listOf("$modifiedColonGte") }
        modifiedColonLt?.apply { localVariableQuery["modified:lt"] = listOf("$modifiedColonLt") }
        modifiedColonLte?.apply { localVariableQuery["modified:lte"] = listOf("$modifiedColonLte") }
        created?.apply { localVariableQuery["created"] = listOf("$created") }
        createdColonGt?.apply { localVariableQuery["created:gt"] = listOf("$createdColonGt") }
        createdColonGte?.apply { localVariableQuery["created:gte"] = listOf("$createdColonGte") }
        createdColonLt?.apply { localVariableQuery["created:lt"] = listOf("$createdColonLt") }
        createdColonLte?.apply { localVariableQuery["created:lte"] = listOf("$createdColonLte") }
        locked?.apply { localVariableQuery["locked"] = listOf("$locked") }
        lockedColonGt?.apply { localVariableQuery["locked:gt"] = listOf("$lockedColonGt") }
        lockedColonGte?.apply { localVariableQuery["locked:gte"] = listOf("$lockedColonGte") }
        lockedColonLt?.apply { localVariableQuery["locked:lt"] = listOf("$lockedColonLt") }
        lockedColonLte?.apply { localVariableQuery["locked:lte"] = listOf("$lockedColonLte") }
        filesize?.apply { localVariableQuery["filesize"] = listOf("$filesize") }
        filesizeColonGt?.apply { localVariableQuery["filesize:gt"] = listOf("$filesizeColonGt") }
        filesizeColonGte?.apply { localVariableQuery["filesize:gte"] = listOf("$filesizeColonGte") }
        filesizeColonLt?.apply { localVariableQuery["filesize:lt"] = listOf("$filesizeColonLt") }
        filesizeColonLte?.apply { localVariableQuery["filesize:lte"] = listOf("$filesizeColonLte") }
        fileType?.apply { localVariableQuery["file_type"] = toMultiValue(this, "csv") }
        emailType?.apply { localVariableQuery["email_type"] = toMultiValue(this, "csv") }
        path?.apply { localVariableQuery["path"] = listOf("$path") }
        pathColonContains?.apply { localVariableQuery["path:contains"] = listOf("$pathColonContains") }
        searchType?.apply { localVariableQuery["searchType"] = toMultiValue(this, "csv") }
        searchFilter?.apply { localVariableQuery["searchFilter"] = listOf("$searchFilter") }
        flsOnly?.apply { localVariableQuery["fls_only"] = listOf("$flsOnly") }
        sharedMailboxId?.apply { localVariableQuery["sharedMailboxId"] = listOf("$sharedMailboxId") }
        orderBy?.apply { localVariableQuery["orderBy"] = toMultiValue(this, "csv") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        with?.apply { localVariableQuery["with"] = listOf("$with") }
        mode?.apply { localVariableQuery["mode"] = listOf("$mode") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/rest/search",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * SharePoint Sites Search api
     * search SharePoint sites
     * @param id The ID of the entity
     * @param includeKw  (optional)
     * @param searchType  (optional)
     * @param limit  (optional)
     * @param query  (optional)
     * @param includeContainer  (optional)
     * @param offset  (optional)
     * @return SearchSharePointSitesResult
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun restSourcesIdQueryGet(id: kotlin.Int, includeKw: kotlin.Boolean? = null, searchType: kotlin.String? = null, limit: kotlin.Int? = null, query: kotlin.String? = null, includeContainer: kotlin.Boolean? = null, offset: kotlin.Int? = null): HttpResponse<SearchSharePointSitesResult> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        includeKw?.apply { localVariableQuery["include_kw"] = listOf("$includeKw") }
        searchType?.apply { localVariableQuery["search_type"] = listOf("$searchType") }
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        query?.apply { localVariableQuery["query"] = listOf("$query") }
        includeContainer?.apply { localVariableQuery["include_container"] = listOf("$includeContainer") }
        offset?.apply { localVariableQuery["offset"] = listOf("$offset") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/rest/sources/{id}/query".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


}
